### ISSUE TITLE
d3fc d3v4 update

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/d3fc#1003]
There are a number of tasks that need to be performed for all the various sub-packages. These include:

 - Update the D3 dependencies to v1.x (many use 0.x at the moment)
 - Consider using greenkeeper
 - Ensure that the bundle is included in the npm release https://github.com/d3fc/d3fc-label-layout/pull/11
 - Test the global dependencies https://github.com/d3fc/d3fc-label-layout/pull/12/
 - Review global naming WRT d3's name flattening, as we now expose everything globally via `fc.`
 - Standardise the GitHub branch protection features

TODO:
 - [x] d3fc-extent
 - [x] d3fc-random-data
 - [x] d3fc-rebind
 - [x] d3fc-financial-feed
 - [x] d3fc-discontinuous-scale
 - [x] d3fc-shape
 - [x] d3fc-sample (only remaining task is D3v4 upgrade for the example code)
 - [x] d3fc-technical-indicator (all done, just waiting on PR https://github.com/d3fc/d3fc-technical-indicator/pull/20)
 - [x] d3fc-data-join
 - [x] d3fc-package-archetype

OTHER:
packages where all of the above are done, but have other remaining work:
  - [x] d3fc-label-layout (need updating to D3v4 - and also has its own `dataJoin`)

**Comment by chrisprice** [comment]
* Standardise the GitHub branch protection features

**Comment by ColinEberhardt** [comment]
@chrisprice is it also worth adding a brief section that indicates who to use within a vanilla JS environment:

https://github.com/d3/d3-scale#installing 

Now that this is tested ;-)

**Comment by ColinEberhardt** [comment]
Is this the correct branch protection set-up?

<img width="802" alt="screen shot 2016-07-14 at 09 35 39" src="https://cloud.githubusercontent.com/assets/1098110/16833303/9bc15796-49a6-11e6-8609-f18a177087ac.png">

It prohibits force push, and merging without status checks - but would it still allow a (non forced) push by an admin?

**Comment by chrisprice** [comment]
Is it worth including the GreenKeeper verify in the status checks that must pass?

**Comment by chrisprice** [comment]
> @chrisprice is it also worth adding a brief section that indicates how to use within a vanilla JS environment

I'm reluctant to do this because I think it'll easily get out of date

**Comment by chrisprice** [comment]
* https://github.com/kentcdodds/validate-commit-msg

**Comment by ColinEberhardt** [comment]
Currently d3fc-sample exposes the following:

    fc.bucket;
    fc.largestTriangleOneBucket;
    fc.largestTriangleThreeBucket;
    fc.modeMedian;

I'd propose moving to the following:

    fc.sampleBucket;
    fc.sampleLargestTriangleOne;
    fc.sampleLargestTriangleThree;
    fc.sampleModeMedian;

WDYT?

**Comment by chrisprice** [comment]
Sounds good to me

**Comment by ColinEberhardt** [comment]
greenskeeper created a bunch of PRs, although I think some of our projects were missing ... worth checking GK is active on the other repos:

https://github.com/d3fc/d3fc-sample/pull/12
https://github.com/d3fc/d3fc-extent/pull/3
https://github.com/d3fc/d3fc-technical-indicator/pull/22

**Comment by chrisprice** [comment]
| Old | New |
| --- | --- |
| annotation/annotation.js | ? |
| annotation/band.js | ? |
| annotation/gridline.js | ? |
| annotation/line.js | ? |
| behavior/behavior.js | ? |
| behavior/pointer.js | ? |
| chart/cartesian.js | ? |
| chart/chart.js | ? |
| chart/smallMultiples.js | ? |
| chart/sparkline.js | ? |
| chart/tooltip.js | ? |
| data/data.js | ? |
| data/random/filter/skipWeekends.js | ? |
| data/random/financial.js | ? |
| data/random/random.js | ? |
| data/random/walk.js | ? |
| data/spread.js | ? |
| fc.js | ? |
| indicator/algorithm/algorithm.js | ? |
| indicator/algorithm/bollingerBands.js | ? |
| indicator/algorithm/elderRay.js | ? |
| indicator/algorithm/envelope.js | ? |
| indicator/algorithm/exponentialMovingAverage.js | ? |
| indicator/algorithm/forceIndex.js | ? |
| indicator/algorithm/macd.js | ? |
| indicator/algorithm/merge.js | ? |
| indicator/algorithm/movingAverage.js | ? |
| indicator/algorithm/relativeStrengthIndex.js | ? |
| indicator/algorithm/stochasticOscillator.js | ? |
| indicator/indicator.js | ? |
| indicator/renderer/bollingerBands.js | ? |
| indicator/renderer/elderRay.js | ? |
| indicator/renderer/envelope.js | ? |
| indicator/renderer/forceIndex.js | ? |
| indicator/renderer/macd.js | ? |
| indicator/renderer/relativeStrengthIndex.js | ? |
| indicator/renderer/renderer.js | ? |
| indicator/renderer/stochasticOscillator.js | ? |
| layout/flexbox.js | ? |
| layout/label.js | ? |
| layout/layout.js | ? |
| scale/dateTime.js | ? |
| scale/discontinuity/identity.js | ? |
| scale/discontinuity/skipWeekends.js | ? |
| scale/scale.js | ? |
| scale/ticks.js | ? |
| series/algorithm/algorithm.js | ? |
| series/algorithm/waterfall.js | ? |
| series/area.js | ? |
| series/axis.js | ? |
| series/bar.js | ? |
| series/boxPlot.js | ? |
| series/candlestick.js | ? |
| series/cycle.js | ? |
| series/errorBar.js | ? |
| series/grouped.js | ? |
| series/line.js | ? |
| series/multi.js | ? |
| series/ohlc.js | ? |
| series/ohlcBase.js | ? |
| series/point.js | ? |
| series/series.js | ? |
| series/stacked/area.js | ? |
| series/stacked/bar.js | ? |
| series/stacked/line.js | ? |
| series/stacked/stack.js | ? |
| series/stacked/stacked.js | ? |
| series/waterfall.js | ? |
| series/xyBase.js | ? |
| svg/axis.js | ? |
| svg/svg.js | ? |
| tool/container.js | ? |
| tool/crosshair.js | ? |
| tool/tool.js | ? |
| util/array.js | ? |
| util/dataJoin.js | ? |
| util/expandRect.js | ? |
| util/extent.js | ? |
| util/fn.js | ? |
| util/fractionalBarWidth.js | ? |
| util/innerDimensions.js | ? |
| util/minimum.js | ? |
| util/percentageChange.js | ? |
| util/render.js | ? |
| util/scale.js | ? |
| util/snap.js | ? |
| util/util.js | ? |

**Comment by chrisprice** [comment]
Superceeded by #944
