### ISSUE TITLE
Possible to Use with React Native?

### ISSUE THREAD

**Issue by joncursi** [ScottLogic/d3fc#1011]
Is it possible to use this library inside of a React native app? I'm wondering if https://github.com/magicismight/react-native-svg can be used internally to convert SVG elements into their native equivalents.

**Comment by joncursi** [comment]
Perhaps it is possible perhaps to inject raw computed d3/svg code into the react native webview component?

https://facebook.github.io/react-native/docs/webview.html

**Comment by ColinEberhardt** [comment]
That's an interesting question! looking at react-native-svn it doesn't appear to support dynamically generated SVG element, however, someone else is looking into this:

https://github.com/magicismight/react-native-svg/issues/75

I think that using a WebView would be a much easier option!

**Comment by joncursi** [comment]
@ColinEberhardt I was actually able to get it to work on React Native in a not-too-hacky way with `WebView`, check out https://github.com/facebook/react-native/issues/8984

I inject the d3/d3fc JavaScript code and HTML code (with d3 and d3fc dependencies specified in `script` tags) into the WebView component to get d3fc charts to render from almost 100% local code. The only thing non-local is the d3 and d3fc dependencies that must be retrieved from a CDN.

**Comment by ColinEberhardt** [comment]
Great, thanks for letting us know how it solved it.
