### ISSUE TITLE
groupedSeries example broken

### ISSUE THREAD

**Issue by PeterVermont** [ScottLogic/d3fc#1013]
The example at: https://d3fc.io/components/series/grouped.html

is not drawing properly. I tested in Chrome and Firefox Developer edition:

![image](https://cloud.githubusercontent.com/assets/889233/17142617/c47fd064-531e-11e6-9e3b-7d56009bbf91.png)

The Codepen also does not work.

**Comment by chrisprice** [comment]
Thanks for the report, this should now be fixed.
