### ISSUE TITLE
extentLinear and extentDate do not support padUnit('percent')?

### ISSUE THREAD

**Issue by joncursi** [ScottLogic/d3fc#1015]
I've upgraded to the latest release of `d3fc` and saw console warnings to upgrade `extent` to `extentLinear` and `extentDate`. After attempting the switch, I noticed that these methods do not seem to support `padUnit('percent')`. I use `percent` over `domain` because I do not know what the accessor values will be, so rather than padding by fixed numbers, I prefer to pad based on a percentage of the value.

**Comment by joncursi** [comment]
I was wrong, it appears that the API for `.pad()` has changed.

In the older version of d3fc, I used `.pad(0.5)`, but now it seems I must be explicit and use `.pad([0.5, 0.5])`

**Comment by chrisprice** [comment]
Sorry it tripped you up but hopefully it was covered in the release notes.
It was an intentional change and part of a more general move away from
overloaded argument types.
