### ISSUE TITLE
Upgrade to d3 4.x

### ISSUE THREAD

**Issue by joncursi** [ScottLogic/d3fc#1016]
D3 `4.2.1` is out, however this package is pinned to the 3.x series. Would it be possible to push out an update that bumps to the 4.x series? Thanks!

**Comment by ColinEberhardt** [comment]
There are some changes in D3v4 that would mean it is a little more work than just bumping the version number. We've actually got bigger plans ...

One of the key features of D3v4 is the way it has been broken up into lots of small modules. We're doing exactly the same thing with d3fc:

https://github.com/d3fc

This includes upgrading to D3v4 and also resisting some of our APIs.

I'd say we are 80% of the way through breaking our components out into separate projects / components. One of the bigger outstanding tasks is how to pull them all together again into a single website / bundle:

https://github.com/d3fc/d3fc

Feel free to start using the new d3fc packages!

**Comment by joncursi** [comment]
Excellent, thank you for the update! New modularity looks great!

**Comment by ColinEberhardt** [comment]
:-)

**Comment by joncursi** [comment]
Hey @ColinEberhardt, in the meantime, is there some way I can use d3 v4 in my project alongside d3fc? I would like to take advantage of some of the new features in v4 but installing v4 will break all d3fc charts. Is it possible to get both versions of D3 inside the project via NPM?

[According to this issue](https://github.com/npm/npm/issues/5499), not really, but was wondering if you had any thoughts. Only thing I can think of is to fork d3v4 as a new repo, change the name of the package to make its identity unique to NPM, and install it via git URL. Any other options?

**Comment by joncursi** [comment]
I tried pulling down vendor'ed copies of d3fc and d3 3.5.17 (last compatible version) so that I can "free up" npm to install and manage the latest version of d3 (4.2.2). However, the following:

```js
const d3 = require('../../vendor/d3.min.js');
const fc = require('../../vendor/d3fc.min.js');
```

produces the following error when `d3fc.min.js` is evaluated:

```
d3fc.min.js:8Uncaught ReferenceError: d3 is not defined
```

Any ideas on what I'm doing wrong?

**Comment by ColinEberhardt** [comment]
d3fc will not work with d3v4, there are a number of breaking changes in d3 that means it will not work.

I think your best option is to wait for our v4 release. You can see our progress here:

https://github.com/d3fc

Most of the code is now in superstar projects, all of which are ready to use right now. W just have a couple of things left to do, 1) migrate Cartesian, and 2) create a top-level bundle.

**Comment by chrisprice** [comment]
I think the problem is the lack of a d3 global or require alias. Easiest
fix is probably to assign d3 to a global (window.d3 = require(...)).

I also think Colin might mean organisation rather than superstar!

**Comment by ColinEberhardt** [comment]
No. Superstar organisation. No need to be modest.

**Comment by kuldarim** [comment]
I'm just curios. When are you planing to release fully supported version with d3.js v4?
