### ISSUE TITLE
slider handles

### ISSUE THREAD

**Issue by mg1075** [ScottLogic/d3fc#341]
The advanced example looks great. 

http://scottlogic.github.io/d3-financial-components/example.html

I think it would be even better if the slider section had handles as is common with other stock charts. 

![image](https://cloud.githubusercontent.com/assets/2031435/7602825/403ca44c-f8ef-11e4-9c16-bcdbcddccc41.png)

**Comment by chrisprice** [comment]
The slider is actually just a d3 brush, so adding in handles is pretty straightforward. The brush is defined [created here](https://github.com/ScottLogic/d3-financial-components/blob/gh-pages/example.html#L281) and here's an example of [adding (quite ugly but the concept is the same) handles](http://bl.ocks.org/mbostock/4349545).
