### ISSUE TITLE
Series are not consistent in their handling of undefined values

### ISSUE THREAD

**Issue by chrisprice** [ScottLogic/d3fc#346]
Area and line (which wrap their d3 counterparts) contain a ```defined``` filter function which allows undefined data values to be skipped. The rest of the series do not have this functionality.

Therefore swapping from a line series to a bar series will cause a runtime error.

I'm not sure if we should remove the functionality from area/line or add it to the others. It seems like nice functionality but forcing an extra filter pass of the data before doing the data-join doesn't sound great either.

**Comment by ColinEberhardt** [comment]
The addition of `xyBase` and `ohlcBase` has resolved this.
