### ISSUE TITLE
Remove functor properties where their application is questionable

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/d3fc#365]
See discussion here:

https://github.com/ScottLogic/d3-financial-components/commit/8062fed341fc13dc0a6822f3dd62cf0f79ecceb2#comments

There are some other examples here:

https://github.com/ScottLogic/d3-financial-components/search?utf8=%E2%9C%93&q=functor

Although they would have to be considered on a case-by-case basis. Some might be an appropriate usage.

**Comment by chrisprice** [comment]
@ColinEberhardt has suggested adding design documentation in each folder which should define whether functors should be used.

**Comment by chrisprice** [comment]
I don't think we need to track this as an issue anymore, I think we're all aware of it.
