### ISSUE TITLE
version information in fc.js has not been updated

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/d3fc#370]
https://github.com/ScottLogic/d3-financial-components/blob/master/src/fc.js#L5

This version has been updated locally, but for some reason wasn't included in the 0.1.1 commit: https://github.com/ScottLogic/d3-financial-components/commit/833eb424ce55b840a7c34448284d2d76b73dfe8c

**Comment by chrisprice** [comment]
The release task currently runs the build (which applies the version) before bumping the version, we should probably make use of the afterBump option in grunt-release. However, watch out for geddski/grunt-release#118.

**Comment by chrisprice** [comment]
There's a PR pending which should allow us to use the postBump hook. I've had a quick look around the other release plugins and they're using the workaround in the PR so I think we just wait for that to land.

**Comment by chrisprice** [comment]
Updated the gruntfile to work with the new version when it's ready (https://github.com/chrisprice/d3-financial-components/tree/370)

**Comment by chrisprice** [comment]
Fixed as part of #431 by removing the grunt task :)
