### ISSUE TITLE
Pull the randomWalk function out of dataGenerator

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/d3fc#374]
For testing a bar series I've found myself wanting a random walk, it's a bit of a pain to have to use the dataGenerator in this context.

**Comment by jleft** [comment]
I'm happy to do this, but I'm not sure which namespace should `randomWalk` reside under?

It used to be in `fc.math`, but this has been removed. Maybe `fc.dataGenerator.randomWalk`? Or is there something more appropriate?

**Comment by chrisprice** [comment]
I almost did this the other day but stopped for the same reason :)

Maybe `fc.dataGenerator` should be renamed `fc.data.financial` and then it could be `fc.data.randomWalk`?

**Comment by jleft** [comment]
Yeah, I like that. Maybe even `fc.data.generator.financial`?

**Comment by chrisprice** [comment]
Maybe `fc.data.random.financial`? Or maybe we drop the `data` bit and just go for `fc.random.financial` & `fc.random.walk`?
