### ISSUE TITLE
Add a tooltip component

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/d3fc#389]

**Comment by chrisprice** [comment]
Is a tooltip distinct from a legend?

**Comment by ColinEberhardt** [comment]
Yes, and no! I think we considered a tooltip to be something that tracks the closest datapoint and displays a text call out nearby.

I am sure this could be constructed by taking a cross hair, hiding the line annotations (to just leave the tracking ball) then decorating to add a legend.

Although with the legend being HTML, there might be a flaw in my plan!

**Comment by chrisprice** [comment]
This looks useful! http://d3-legend.susielu.com/#summary

**Comment by bjedrzejewski** [comment]
I will work on adding a tooltip component

**Comment by duhaime** [comment]
@ColinEberhardt is there any documentation on how the tooltip can be used with a scatterplot?

**Comment by duhaime** [comment]
Ah, it looks like you use a quadtree in your HathiTrust example (which is awesome!) https://github.com/ColinEberhardt/d3fc-webgl-hathi-explorer/blob/master/index.js#L62

Are there any hooks in d3fc to use "GPU picking" in order to identify which element is under the cursor?

**Comment by chrisprice** [comment]
There's nothing built in but as you asked for hooks I assume you don't mind
getting your hands dirty!

If I were attempting it, I'd start with a WebGL point series and an
OffscreenCanvas. I'd then use decoration on the series to assign fill
colours using some reversible mechanism. Then render the series and extract
the image bitmap to perform lookups into. Playing with the point size and
the order of the data should give some control over hit areas.

If performance is a concern then there's a couple of other options to try
but I'd start here.

**Comment by duhaime** [comment]
Thanks for the follow up!

This is interesting--I hadn't ever thought the order of data would have any impact on GPU picking. How does the order impact the selection? I thought we would just render each item with a distinct color and then read the color under the user's cursor to determine which data item was being hovered (if any)...

**Comment by chrisprice** [comment]
If I've understood GPU picking correctly, it would only matter in the case of overlapping points. However, this can be relatively common even with small datasets, as it's often useful to increase the size of a point to increase its effective hit area.

**Comment by duhaime** [comment]
Ah yes, I see what you mean! I guess one gets into z-sorting and blending once the points start to overlap as well...

I'm working on some plots now that may need to get quite large. If they do and I get a chance to try some GPU picking with d3fc I'll follow up in this thread. Thanks again for your comments!
