### ISSUE TITLE
Add side-by-side grouped chart type

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/d3fc#390]
Currently our stacked bar series demonstrates a single form of 'grouped' series. We should also consider adding side-by-side grouped charts ...

**Comment by chrisprice** [comment]
@ColinEberhardt  can you provide a bit more detail on this one? Not sure what you mean.

**Comment by ColinEberhardt** [comment]
> @ColinEberhardt can you provide a bit more detail on this one? Not sure what you mean.

Done :-)

**Comment by janakerman** [comment]
I've made a couple of changes that should make it possible to display 100% stacked bars. I'm just looking at adding a visual test before I push up a pull request. Adding stacked area / line is as simple as duplicating the stackedBar series and changing wrapped series as appropriate (this does incur quite a bit of code repetition, so we can discuss a better design.)

**Comment by chrisprice** [comment]
Thanks @janakerman, it would be good to see those changes: maybe you could link to a diff or create a WIP PR?

It sounds like now might be the appropriate time to see if we can adopt the [indicator pattern](https://github.com/ScottLogic/d3fc/blob/master/src/indicator/design-guidelines.md) for stacked bars. I think in this case the `d3.layout.stacked` would play the part of both the calculator and algorithm, and the existing series (and the new ones) would become renderers?

As far as code repetition, the [merge algorithm](https://github.com/ScottLogic/d3fc/blob/master/src/indicator/algorithm/merge.js) and the [moving average use of it](https://github.com/ScottLogic/d3fc/blob/master/src/indicator/algorithm/movingAverage.js) are good examples of how we've dealt with code repetition so far. I wonder if that might be an appropriate choice in this case?

**Comment by chrisprice** [comment]
Also @janakerman, I think #391 might be a more appropriate issue for the specific changes your making? I'm going to change this issue to be specifically side-by-side bars.

**Comment by janakerman** [comment]
@ColinEberhardt - Just to confirm.. something like?

 ![this](http://www.jidesoft.com/images/bar-chart-group.png)

(I'll copy the styling exactly - of course!)

**Comment by chrisprice** [comment]
Might be worth playing with the [Kibana charts](http://demo.elastic.co/packetbeat) for some inspriation.

**Comment by ColinEberhardt** [comment]
Done
