### ISSUE TITLE
Styling stacked bar series is hard

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/d3fc#400]
The stacked bar series has the following structure:

![screen shot 2015-06-04 at 08 18 54](https://cloud.githubusercontent.com/assets/1098110/7978897/8a6100e0-0a92-11e5-8c67-51a6140be02c.png)

It is a collection of bar series, each with a parent `g.stacked-bar`. To set the color for each series you would expect to be able to decorate as follows:

        var stack = fc.series.stackedBar()
            .decorate(function(sel) {
                sel.attr('fill', function(d, i) {
                    return color(i);
                });
            });

This sets the `fill` attribute for the `g.stacked-bar` elements. However, the fill color for each bar is determined by the CSS selector `.bar>path`. which has a higher specificity.

This can be solved by setting the `fill` style on the path directly:

    .decorate(function(sel) {
        sel.each(function(d, i) {
            d3.select(this)
              .selectAll('path')
              .style('fill', color(i));
        }); 
    });

But the need to 'burrow' into the internal structure is a bit ugly.

**Comment by ColinEberhardt** [comment]
I've been playing around with this and really like it. However, it took a while to get an example up and running, quite a few scales and value accessors to get right!

This series will benefit from a clear and simple example on the website. 

I re-implemented Graham's example using the cycle series, which went pretty well:

    d3.json('data.json', function(error, data) {
        var parseDate = d3.time.format('%Y%m%d').parse;

        // parse the data / coerce types
        data.forEach(function(d) {
          d.date = parseDate(d.date);
          d.itemsSold = +d.items_sold;
        });

        var dayScale = d3.scale.linear()
            .domain([-0.5, 6.5])
            .range([0, width]);

        var salesScale = d3.scale.linear()
            .domain(fc.utilities.extent(data, 'itemsSold'))
            .range([height, 0])
            .nice();

        var subScale = d3.scale.linear()
            .domain(fc.utilities.extent(data, 'date'));

        var lineSeries = fc.series.line()
            .xValue(function(d) { return d.date; })
            .yValue(function(d) { return d.itemsSold; });

        var cycle = fc.series.cycle()
            .barWidth(fc.utilities.fractionalBarWidth(0.9))
            .yScale(salesScale)
            .xScale(dayScale)
            .xValue(function(d) { return d.date.getDay(); })
            .subScale(subScale)
            .subSeries(lineSeries);

        container.append('g')
            .datum(data)
            .call(cycle);
    });

Although as soon as I added the 'baseline', the average price for each day of the week, it became very ugly! It is a real pain having to repeat the same nesting that the cycle series performs.

I also had to add some manual padding around the `dayScale`, which I notice the cycle series should take care of. I'll take a close look later.

This functionality could be baked in to the cycle series, or perhaps added as a form of axis?

**Comment by ColinEberhardt** [comment]
> I also had to add some manual padding around the dayScale, which I notice the cycle series should take care of. I'll take a close look later.

Ignore that - your half-width calculation isn't for padding the axis :-)

**Comment by ColinEberhardt** [comment]
Relates to #629 - although the problem described here appears to no longer be an issue.

**Comment by jdunkerley** [comment]
@ColinEberhardt are we happy #640 closes this?
