### ISSUE TITLE
Name change!!!

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/d3fc#423]
Let's stick with D3FC but drop the direct reference to 'financial components'

**Comment by chrisprice** [comment]
d3fc or D3FC? :)

**Comment by chrisprice** [comment]
Created a new repo to redirect both the repo and website to this one when it is renamed. Assumed that we'll go for d3fc as the name?

https://github.com/ScottLogic/d3-financial-components-redirect

**Comment by ColinEberhardt** [comment]
Yes, d3fc as the repo name makes sense - although I don't think we need to manually redirect traffic ...

https://help.github.com/articles/renaming-a-repository/

**Comment by chrisprice** [comment]
:neutral_face: :hand:

**Comment by chrisprice** [comment]
http://stackoverflow.com/questions/28371669/renaming-a-published-npm-module

**Comment by chrisprice** [comment]
Repo renamed and website redirect setup.
[ ] Publish new version to npm
[ ] Deprecate old npm module
[ ] Update website

**Comment by ColinEberhardt** [comment]
[ ] update readme to reflect name change

I was thinking something along the lines of:

#D3FC - Charting Components

**Comment by ColinEberhardt** [comment]
Ok, so markdown is ignored in the GitHub mobile website

**Comment by chrisprice** [comment]
Sorry didn't spot this comment, I've changed it to d3fc for now. Also I've been sticking with lowercase rather than uppercase?

**Comment by chrisprice** [comment]
* [ ] Change distribution build names

**Comment by ColinEberhardt** [comment]
lowercase looks fine to me.

**Comment by chrisprice** [comment]
* [] Grep codebase for d3-financial-components (don't forget gh-pages)

**Comment by chrisprice** [comment]
Published a new version to npm under d3fc but I think I'm hitting cache issues. I'm going to wait until tomorrow to follow the deprecate instructions above.

**Comment by chrisprice** [comment]
All done :)

(probably)
