### ISSUE TITLE
Extract range function to fc.util.range

### ISSUE THREAD

**Issue by chrisprice** [ScottLogic/d3fc#437]
It's turning up in almost every file now -

```js
        // ordinal axes have a rangeExtent function, this adds any padding that
        // was applied to the range. This functions returns the rangeExtent
        // if present, or range otherwise
        function range(scale) {
            return scale.rangeExtent ? scale.rangeExtent() : scale.range();
        }
```

Looks like d3 has the [same problem](https://github.com/mbostock/d3/blob/master/src/scale/scale.js). Might be worth pulling over their scaleExtent function as well (not sure when it's useful though)?

**Comment by ColinEberhardt** [comment]
Good point, I was considering doing that myself ... as I cut and paste the three-line comment that accompanied it ...

**Comment by chrisprice** [comment]
This was implemented a while back as `fc.util.scale.range`.
