### ISSUE TITLE
Delete (or otherwise deprecate) fc.util.simpleDataJoin

### ISSUE THREAD

**Issue by chrisprice** [ScottLogic/d3fc#443]

**Comment by ColinEberhardt** [comment]
@janakerman - I've actually started working on this, I am guessing you didn't get started yet?

**Comment by janakerman** [comment]
@ColinEberhardt - I started looking into this but I only managed to get a negligible amount of work done - I've been distracted with other work! Please feel free to carry on. Also, sorry for my 4 day response time!
