### ISSUE TITLE
Ensure our components provide the correct context to functional properties

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/d3fc#446]
See the fix here: https://github.com/ScottLogic/d3fc/pull/439

For all functional properties we should ensure that the 'this' context parameter is the relevant DOM element, the first parameter is the joined data and the second is the index.

**Comment by chrisprice** [comment]
I realised last night that there's a bit of an edge case. The change in #439 allows you to force an index as well as pass in an array of n != 0. Maybe we restrict it to only working with n == 1? 

It might also simplify the code a little -

```js
var bar = function(data, index) {

    return data.map(function(d, i) {
        var xValue = x.call(this, d, index || i),
            yValue = y.call(this, d, index || i),
            barHeight = height.call(this, d, index || i),
            barWidth = width.call(this, d, index || i);
        // ...
```

```js
var bar = function(data, index) {

    function pathGenerator(d, i) {
        var xValue = x.call(this, d, i),
            yValue = y.call(this, d, i),
            barHeight = height.call(this, d, i),
            barWidth = width.call(this, d, i);
        // ...
    }

    return index !== undefined ? data.map(pathGenerator) : pathGenerator.call(this, data, index);
```

**Comment by ColinEberhardt** [comment]
That's a neater implementation, definitely worth doing when rolling this out across the svg components.

**Comment by chrisprice** [comment]
I don't think this is a problem anymore as we now calculate all values local to the series before passing them off to the svg components (to allow us to position within the `g` elements).
