### ISSUE TITLE
Submit to 'awesome d3'

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/d3fc#456]
I'll raise a PR to submit d3fc to 'awesome d3'  https://github.com/wbkd/awesome-d3

But thought I'd raise an issue as a place to discuss some of the other D3 frameworks / libraries. We might be able to take inspiration from some of these.

**Comment by ColinEberhardt** [comment]
Someone else did this for us ...

**Comment by chrisprice** [comment]
Really? Awesome :+1:
