### ISSUE TITLE
Specialised functors for property accessors?

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/d3fc#457]
This one might be a bit controversial, but I am getting a bit sick of seeing this same boiler-plate over and over again:

    value(function(d) { return d.close; })

We could use a functor that takes string values and provides the same function as above:

    value('close')

I know that with ES6 arrows will give us a concise syntax `value(d => d.close)`, but I do wonder how long it will be before D3 updates their API to be more ES6-friendly.

**Comment by chrisprice** [comment]
I'm firmly on the opposite side of the fence. It looks too much like magic and is ambiguous.

**Comment by chrisprice** [comment]
We did discuss this offline but my rather terse comment above pretty much sums it up. Ultimately, arrow functions are the neatest solution but we don't want to enforce a dependency on Babel and the like. Therefore we stick with the slightly more verbose syntax but users are free to use arrow functions if they wish.
