### ISSUE TITLE
Replace the website main chart with something more ...

### ISSUE THREAD

**Issue by chrisprice** [ScottLogic/d3fc#460]
* Exciting
* Interactive
* Themed
* etc.

**Also fix the colour scheme of the other charts**

**Comment by chrisprice** [comment]
I like coinbase's homepage... https://exchange.coinbase.com/

**Comment by ColinEberhardt** [comment]
It does look pretty cool - definitely one of the best background videos I've seen. They're usually a lot more gratuitous. It would be fun to implement their chart, it has some subtly different features:

![screen shot 2015-07-02 at 22 01 38](https://cloud.githubusercontent.com/assets/1098110/8487766/02407d82-2106-11e5-821c-fb21114578e6.png)

Like the way the crosshair highlights the closes volume bar. It would be interesting to see how that could be achieved with d3fc.

**Comment by jleft** [comment]
> I like coinbase's homepage... https://exchange.coinbase.com/

If we would like a video like that, I'd be happy to _attempt_ to make one - just let me know :smiley:.

**Comment by chrisprice** [comment]
Ah I forgot that we'd discussed this offline. I'm proposing creating something which looks like the video but is actually rendered in real-time...

**Comment by ColinEberhardt** [comment]
That's sounds nuts! I look forward to seeing it.

On Fri, Jul 3, 2015 at 9:28 am, ScottLogic/d3fc
<reply@reply.github.com>
wrote:
Ah I forgot that we'd discussed this offline. I'm proposing creating something
which looks like the video but is actually rendered in real-time...

—
Reply to this email directly or view it on GitHub
[https://github.com/ScottLogic/d3fc/issues/460#issuecomment-118274388] .[https://github.com/notifications/beacon/ABDBfnJTf7Qqrakl14dT6kKvWzHoHAU3ks5oZj87gaJpZM4FPs_L.gif]

**Comment by jleft** [comment]
> Ah I forgot that we'd discussed this offline. I'm proposing creating something which looks like the video but is actually rendered in real-time...

Cool, no problem, I thought that was more likely than a video!

**Comment by chrisprice** [comment]
[Created](http://blog.scottlogic.com/2015/08/06/an-adventure-in-svg-filter-land.html) but due to shoddy browser support probably not one for the front page.

**Comment by chrisprice** [comment]
All change (2bf4206de72876ee4b4044f2ae88f691c54400eb), so no longer relevant
