### ISSUE TITLE
Add d3fc playground to website

### ISSUE THREAD

**Issue by chrisprice** [ScottLogic/d3fc#469]
See similar ones for [less](http://less2css.org/) or [typescript](http://www.typescriptlang.org/Playground).

**Comment by bjedrzejewski** [comment]
@jdunkerley and myself are looking to do something on this one together (mentioning in case someone already started).

**Comment by jdunkerley** [comment]
Have put together a rough prototype based around the Ace Editor:
http://jdunkerley.github.io/d3fcPlayground/

**Comment by bjedrzejewski** [comment]
Looking great so far! I think there will be some work on the neat examples now and work integrating it.... Also I really like the light theme  :)

**Comment by chrisprice** [comment]
Thanks @jdunkerley, I think it's a good first stab. I agree with the comments above and would add that we should establish out the design and feature-set we want before we continue much further. 

Also have you seen [CodeMirror](https://codemirror.net/demo/folding.html)? I have a mild preference for it and it is the editor behind the less example.

**Comment by jdunkerley** [comment]
Thanks @chrisprice, agree need to have a discussion on what we want the initial version to be and overall design of the both playground and site.

We looked briefly at CodeMirror as well as Ace. Had seen Ace used before so tried that one first. Will take a look at CodeMirror.

**Comment by chrisprice** [comment]
Looking at how we're using it, I think CodeMirror should result in less
code (it can be configured by a JSON object rather than lots of
set/get-ters).

**Comment by jdunkerley** [comment]
Will go try in a minute and put an update out

**Comment by chrisprice** [comment]
Now using codepen instead
