### ISSUE TITLE
No decorate on redenders or multi

### ISSUE THREAD

**Issue by chrisprice** [ScottLogic/d3fc#471]
Very hard to target the different indicators on a chart (unless I'm missing something).

**Comment by ColinEberhardt** [comment]
Good point, also linearTimeSeries - although by entirely obvious what the decorate selection should be. I have found myself wanting to alter some of the elements constructed by this component.

**Comment by chrisprice** [comment]
I'll pick this up for multi. As you say, I don't really know where to start with linearTimeSeries...

**Comment by chrisprice** [comment]
Spun out the above issue to cover linearTimeSeries.
