### ISSUE TITLE
Add path data generator component

### ISSUE THREAD

**Issue by jleft** [ScottLogic/d3fc#480]
D3 has some [great SVG path data generators](https://github.com/mbostock/d3/wiki/SVG-Shapes#path-data-generators). However, sometimes it makes sense to use the path data instructions directly, but constructing this can often involve some fairly ugly string concatenation; [OHLC, for example](https://github.com/ScottLogic/d3fc/blob/master/src/svg/ohlc.js#L26-30):

```js
var moveToLow = 'M' + xValue + ',' + yLow,
    verticalToHigh = 'V' + yHigh,
    openTick = 'M' + xValue + ',' + yOpen + 'h' + (-halfWidth),
    closeTick = 'M' + xValue + ',' + yClose + 'h' + halfWidth;
return moveToLow + verticalToHigh + openTick + closeTick;
```

Creating a component which handles this in a friendlier manner could be of benefit. I was thinking of something like this:

```js
var path = fc.svg.path()
    .moveTo(xValue, yLow)
    .verticalLineTo(yHigh)
    .moveTo(xValue, yOpen)
    .horizontalLineToRelative(-halfWidth)
    .moveTo(xValue, yClose)
    .horizontalLineToRelative(halfWidth);
return path();
```

I've written some tests for this and will finish the implementation, assuming we think this is a worthwhile addition? Any ideas or suggestions welcome!

Credit to @chrisprice for giving me the idea a while ago :smiley:

**Comment by ColinEberhardt** [comment]
Nice idea, reminds me of this:

https://github.com/VerbalExpressions/CSharpVerbalExpressions/

**Comment by bjedrzejewski** [comment]
@jleft are you still working on it? Sounds like a great idea and we have some time in London right now- let me know and maybe I can help.

**Comment by jleft** [comment]
@bjedrzejewski - I haven't worked on this for a while, so please feel free to pick it up :smiley: I'll see if I've got anything worth pushing up (might be useful as a starting point), but won't be able to do so until this evening.

**Comment by bjedrzejewski** [comment]
@jleft ok, no worries. I will see if you find something that you have worked on and pick it up from there tomorrow/once you pushed.

**Comment by chrisprice** [comment]
d3-path beat us to it.
