### ISSUE TITLE
Enhance the data package

### ISSUE THREAD

**Issue by chrisprice** [ScottLogic/d3fc#487]
Basically plagiarise the ideas from [this page](http://turingfinance.com/interactive-stochastic-processes/). 

* [ ] Implement the Merton Jump-Diffusion Model and the Heston Stochastic Volatility Model.
* [ ] Add more compelling data generator documentation/example.

**Comment by chrisprice** [comment]
Also check out the links at the top of the pages for sample code.

**Comment by jdunkerley** [comment]
Newest link is http://stuartreid.co.za/interactive-stochastic-processes/

**Comment by chrisprice** [comment]
Thanks @jdunkerley, I'd spotted it had broken but hadn't worked out where it had gone.

**Comment by chrisprice** [comment]
Superseded by https://github.com/d3fc/d3fc-random-data/issues/3
