### ISSUE TITLE
Bower package

### ISSUE THREAD

**Issue by jleft** [ScottLogic/d3fc#499]
Would it be worth registering d3fc as a [Bower](http://bower.io/) package?

**Comment by chrisprice** [comment]
I have a personal dislike of bower (don't understand why you'd not use npm)
but don't see any harm in adding a metadata file for it

**Comment by ColinEberhardt** [comment]
Adding to bower is very easy, just add a `bower.json` then run a one-off `bower register` command.

However there is one issue, bower links to tagged version of the git repo, however we do not add our distribution code to git, or update the version number in `fc.js`, so the bower package will be pretty ineffective.

... which mirrors the experience I have had with a few bower packages in the past!

**Comment by chrisprice** [comment]
I think [this](https://gofore.com/ohjelmistokehitys/stop-using-bower/) settles it.

**Comment by PeterVermont** [comment]
Found this via google search -- disappointed not to have bower package. I am new-ish to js and use brackets with a bower package manager extension

**Comment by ColinEberhardt** [comment]
Hi @PeterVermont we don't want to include our bundled (compiled) code within the repository. For that reason (among others) we do not publish to bower. However, you can still use bower to define your dependency to d3fc using the npm package from the npm CDN as follows:

```
bower install https://npmcdn.com/d3fc@11.0.0/dist/d3fc.bundle.min.js --save
```

Hope that helps.

**Comment by PeterVermont** [comment]
Thank you!
