### ISSUE TITLE
No decorate property on indicator renderers

### ISSUE THREAD

**Issue by jleft** [ScottLogic/d3fc#520]
Many of the components expose a decorate property, but the indicator renderers don't. I think it makes sense for the renderers to have this functionality too.

**Comment by chrisprice** [comment]
Agreed, the renderers are essentially specialised series so it definitely makes sense. I assume it was just an oversight.

**Comment by chrisprice** [comment]
#534 allows decoration but would someone be able to provide some useful examples of decoration?

**Comment by chrisprice** [comment]
Assuming this now works.
