### ISSUE TITLE
Order of elements created by data join should match the order of their corresponding datums

### ISSUE THREAD

**Issue by jleft** [ScottLogic/d3fc#528]
The elements in data join's enter selection are appended, so their order may not correspond to the order of the data.

Rather than [appending](https://github.com/mbostock/d3/wiki/Selections#append) the elements, they could be [inserted](https://github.com/mbostock/d3/wiki/Selections#insert) (using `selection.insert()`), to maintain order.

> For enter selections, the before selector may be omitted, in which case entering elements will be inserted immediately before the next following sibling in the update selection, if any. This allows you to insert elements into the DOM in an order consistent with bound data. Note, however, the slower selection.order may still be required if updating elements change order.

Source: https://github.com/mbostock/d3/wiki/Selections#insert

---

This would be particularly useful when the z-index is important, for example the ordering of series in multi.

**Comment by chrisprice** [comment]
To highlight and paraphrase a point from that quote -

> Doing the above will ensure that order is correct on enter so long as the data is not re-ordered. In the case that the data is re-ordered it will still be necessary to use selection.order.

We can't guarantee the ordering by making this change but it will, at little to no cost, minimise the  post-processing done by selection.order.
