### ISSUE TITLE
Should multi series always order elements in the same order as specified in the series array?

### ISSUE THREAD

**Issue by jleft** [ScottLogic/d3fc#537]
It can be confusing that the ordering of the series (specified in an array passed to multi's series method) doesn't always match the order of the series' associated groups in the DOM. Should multi always guarantee this ordering?

Current behaviour:

```js
var mutli = fc.series.multi()
    .series([a, b, c]);

// call multi on selection. output:
// <g><!-- series a --></g>
// <g><!-- series b --></g>
// <g><!-- series c --></g>

multi.series([a, c, b]);

// call multi on selection
// B and C remain in the same order
// output:
// <g><!-- series a --></g>
// <g><!-- series b --></g>
// <g><!-- series c --></g>
```

Suggested change to behaviour:

```js
var mutli = fc.series.multi()
    .series([a, b, c]);

// call multi on selection. output:
// <g><!-- series a --></g>
// <g><!-- series b --></g>
// <g><!-- series c --></g>

multi.series([a, c, b]);

// call multi on selection
// B and C have swapped order - matching the order in the series array
// output:
// <g><!-- series a --></g>
// <g><!-- series c --></g>
// <g><!-- series b --></g>
```

If not, I think this behaviour should be documented.

I'm happy to either update multi and write some tests, and/or update the docs - which ever is preferable.

**Comment by chrisprice** [comment]
Thoughts -
* + More logical behavior based on the name: `d3.series.multi` implies that it should be used to display multiple series and therefore it follows they should be in the order specified.
* - Will add a slight performance hit which isn't always going to be necessary.
* + In most of use-cases we don't modify the order of the `series` (or modify `series` at all) so there'll be minimal performance impact for our components.

As I've not measured the performance impact and to date we've not worried too much about performance, I say we make the change.
