### ISSUE TITLE
Support merging of properties in d3.selection.prototype.layout

### ISSUE THREAD

**Issue by chrisprice** [ScottLogic/d3fc#543]
`d3.selection.prototype.layout({})` should apply the key/values in addition to what is already there, replacing key values as appropriate.

Currently the behavior is to replace everything with the specified key/values, including removing non-conflicting values.

This would remove the need to mix constant and variable values being assigned such as in - https://github.com/ScottLogic/d3fc/pull/518/files#diff-54543ef480c3f51e0d0698f36a9ddfd7R93

**Comment by ColinEberhardt** [comment]
With our d3v4 release we will no longer use flexbox layout - see https://github.com/d3fc/d3fc-element
