### ISSUE TITLE
Add band annotation documentation

### ISSUE THREAD

**Issue by chrisprice** [ScottLogic/d3fc#544]

**Comment by bjedrzejewski** [comment]
@chrisprice could you provide a bit more details?

**Comment by chrisprice** [comment]
Erm can't really remember, at a guess: do we have a band annotation and is it documented?

**Comment by ColinEberhardt** [comment]
Yes and no respectively!

**Comment by chrisprice** [comment]
In that case the issue means we should add some documentation for it :)
