### ISSUE TITLE
fc.data.random.walk doesn't follow the component pattern

### ISSUE THREAD

**Issue by chrisprice** [ScottLogic/d3fc#545]
```function(period, steps, mu, sigma, initial) {```

Should be something like -

```var w = walk().period(a).steps(b).mu(c).sigma(d)(initial)```

**Comment by bjedrzejewski** [comment]
I will work on that.

**Comment by bjedrzejewski** [comment]
@chrisprice under this issue I will also add random walk documentation to the website, as it is missing (used under financial), but is rather useful.
