### ISSUE TITLE
Add a 'classed' property to the series

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/d3fc#555]
A common use-case is to add multiple series to a chart and then apply styles to each of them. Currently this requires the use of `decorate`:

    var macdLine = fc.series.line()
        .xValue(xValue)
        .yValue(function(d, i) { return root(d).macd; });

    var signalLine = fc.series.line()
        .xValue(xValue)
        .yValue(function(d, i) { return root(d).signal; });

    var divergenceBar = fc.series.line()
        .xValue(xValue)
        .yValue(function(d, i) { return root(d).divergence; });

    var multiSeries = fc.series.multi()
        .series([divergenceBar, macdLine, signalLine])
        .decorate(function(g, data, index) {
            g.enter()
                .attr('class', function(d, i) {
                    return 'multi ' + ['divergence', 'macd', 'signal'][i];
                });
            decorate(g, data, index);
        });

With the above code adding classes to the multi-containers.

I think the above code is a little complex when all the user wants to do is style each series. How about we add a 'classed' property to each series:

    var macdLine = fc.series.line()
        .classed('macd')
        .xValue(xValue)
        .yValue(function(d, i) { return root(d).macd; });

    var signalLine = fc.series.line()
        .classed('signal')
        .xValue(xValue)
        .yValue(function(d, i) { return root(d).signal; });

    var divergenceBar = fc.series.bar()
        .classed('divergence')
        .xValue(xValue)
        .yValue(function(d, i) { return root(d).divergence; });

    var multiSeries = fc.series.multi()
        .series([divergenceBar, macdLine, signalLine]);

This would add the given class to each of the containers the series constructs, rather than applying it to the multi- containers.

**Comment by chrisprice** [comment]
Which container the series constructs?

**Comment by chrisprice** [comment]
Ah "containers", in that case I think decorate isn't too bad a solution -

```
var divergenceBar = fc.series.bar()
    .decorate(function(g) { g.classed('divergence'); })
    .xValue(xValue)
    .yValue(function(d, i) { return root(d).divergence; });
```
