### ISSUE TITLE
Support transitions with the chart components

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/d3fc#563]
Both our chart components cannot be called on a transition because they use various selection methods which are not available on transitions (`attr`, `html`, ...). Which makes sense.

However, as the various series / axis components support transitions it's a shame that you cannot make use of this feature when using the components in conjunction with charts.

I quickly hacked together a modified chart component that optionally converts the selections used for the axes / series into transitions:

https://github.com/ColinEberhardt/d3-financial-components/commit/15595130b70b3628a5ad7c4ba96986db085f7230

The char component exposes a `transitionDuration` property which is used to determine whether to use transitions or selections.

**Comment by chrisprice** [comment]
That doesn't look quite right to me, but I'll admit my transition knowledge is a bit limited. @jleft any thoughts?

**Comment by ColinEberhardt** [comment]
Just to clarify, does it not look quite right from an implementation perspective
or from the perspective of the API that the Cartesian chart exposed to support
transitions (or both)?

On Wed, Sep 23, 2015 at 9:18 a.m., ScottLogic/d3fc
<reply@reply.github.com>
wrote:
That doesn't look quite right to me, but I'll admit my transition knowledge is a
bit limited. @jleft [https://github.com/jleft] any thoughts?

—
Reply to this email directly or view it on GitHub
[https://github.com/ScottLogic/d3fc/issues/563#issuecomment-142526805] .[https://github.com/notifications/beacon/ABDBfr8sQwkk3r-bcGQEmMDwEk1V6MFeks5o0lfygaJpZM4GCK_M.gif]

**Comment by chrisprice** [comment]
Both: my understanding of transitions were that they should propagate
through selections (by magic somehow...).

I know in d3v4 they've exposed all properties on transitions to make this
easier.

**Comment by ColinEberhardt** [comment]
> I know in d3v4 they've exposed all properties on transitions to make this
easier.

Just out of interest, where have you seen this discussed? I've previously had a look at the D3 v.4 milestone issues:

https://github.com/mbostock/d3/milestones/4.0

But I am guessing this isn't the complete scope of v4?

**Comment by chrisprice** [comment]
Ah no I've got my wires crossed, I was thinking of the enter selection API -
> Enter selections no longer have a special subclass, and thus support all selection methods.

**Comment by ColinEberhardt** [comment]
Ah, that makes sense. I couldn't quite get my head round how transition and selection could be unified.

There are still a few things about how transitions work that baffle me a little, so I'll do a bit more digging around.
