### ISSUE TITLE
CartesianChart exposes too many scales

### ISSUE THREAD

**Issue by djmiley** [ScottLogic/d3fc#564]
Should cartesianChart expose xScale() and yScale() only?

It currently exposes xXScale(), xYScale(), yXScale() and yYScale().

**Comment by ColinEberhardt** [comment]
Yeah, it's designed to create six dimensional visualisations!
(OK, it's a bug)
Well spotted!

On Thu, Sep 24, 2015 at 1:37 p.m., ScottLogic/d3fc
<reply@reply.github.com>
wrote:
Should cartesianChart expose xScale() and yScale() only?

It currently exposes xXScale(), xYScale(), yXScale() and yYScale().
