### ISSUE TITLE
Add visual tests and website error checking to CI

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/d3fc#569]
At the moment the website is broken (https://github.com/ScottLogic/d3fc/commit/6647a8d240fb4cdf2995b1e3eb74984fb8a5e1f8)

It would be great if the CI build could check whether the website or visual tests log any errors to the console.

**Comment by bjedrzejewski** [comment]
Are we simply looking for any script error in visual test to fail the build? I can look into that.

**Comment by ColinEberhardt** [comment]
@bjedrzejewski yes, any script error in visual tests or the website should fail the build. As you can see from the issues I've linked, this could have caught quite a few bugs early-on.

It would be great if you came up with a solution to this :-)

**Comment by bjedrzejewski** [comment]
Ok, I will work on this then. I notices that we have quite a few problems linked to this.

**Comment by bjedrzejewski** [comment]
I am currently investigating 3 options:

1. Running Karma in Travis CI and having simple test that checks for console errors
2. Running Karma from Grunt and having simple test that checks for console errors (I think Karma as a separate CI check is cleaner and makes normal build faster).
3. Trying to add the tests directly in Jasmine using PhantomJS- maybe this is the simplest and the most lightweight option, but it is somewhat limited (other browsers etc), but may be just what we need.

@ColinEberhardt @chrisprice @jdunkerley any thoughts?

**Comment by chrisprice** [comment]
Selenium driving BrowserStack? They offer all platforms and free for open
source.

Selenium also offers the route of screenshot diffing (a controversial
subject!) in the future.

**Comment by bjedrzejewski** [comment]
I thought you wanted something JS based. BrowserStack is definitely powerful, but I don't think it can serve well as a quick 'does it build well' test? 

Maybe some headless based Selenium testing is the first phase and once we are confident, we can move to browser stack?

**Comment by ColinEberhardt** [comment]
For this type of testing I think it makes sense to use a real browser,
rather than a headless JS implementation. We do not have any form of tests
at the moment that pick up cross-browser issues, something we have seen
recently ...

https://github.com/chrisprice/d3fc/commit/ca639c6011d3e8f1d8abc484c80aea2882310bc8

On Thu, Oct 15, 2015 at 11:52 AM, Bartosz Jedrzejewski <
notifications@github.com> wrote:

> I thought you wanted something JS based. BrowserStack is definitely
> powerful, but I don't think it can serve well as a quick 'does it build
> well' test?
>
> Maybe some headless based Selenium testing is the first phase and once we
> are confident, we can move to browser stack?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ScottLogic/d3fc/issues/569#issuecomment-148350198>.
>



-- 
Regards,
Colin E.

**Comment by chrisprice** [comment]
To be clear, I just mean a simple selenium script to fire up all the URLs
and check the console for errors, nothing fancy.

**Comment by bjedrzejewski** [comment]
Ok, so I think we have the strategy. I will be looking what we can do with

http://webdriver.io/ / Travic CI / BrowserStack

Hopefully good cross browser testing. Do we have a ScottLogic account on BrowserStack, or should we use personal ones while in testing / development?

**Comment by bjedrzejewski** [comment]
@chrisprice - Yes, fire all the pages across all the browsers and check for JS errors as the first phase.

**Comment by bjedrzejewski** [comment]
@ColinEberhardt @chrisprice  I have added a basic passing test into:

https://github.com/bjedrzejewski/d3fc/tree/webdriver

I am not sure if this is good enough for pull request, but I reckon it is a decent starting point for more work. I don't know yet how to integrate it with Travis CI so that Travis first deploys the updated website and then runs the test from browserstack. I think we need an open source account on browserstack as well. At the moment if you want to check the work, you will need to create your own free account.

**Comment by chrisprice** [comment]
That looks like a good starting point to me. I'm not sure it's PR-ready yet, it needs some features (e.g. checking the console for errors and iterating over all the pages) adding  and a bit of a cleanup first.

I would expect travis to run against the site hosted locally (as part of the build).

I'll request the account from browserstack.

**Comment by bjedrzejewski** [comment]
I managed to get the local testing working, but it requires small connection utility to be run. I think the first pull request would be local testing to check for console errors with instructions what to switch on and then we can move to Travis CI automation from there.

@chrisprice Let me know once you have the account from browserstack as I will run out of my free minutes :)

**Comment by chrisprice** [comment]
@bjedrzejewski they are asking which products we want, do you know?

**Comment by bjedrzejewski** [comment]
@chrisprice we are interested in the automated testing- I guess locally and remotely against the most popular browsers- latest firefox, chrome, safari, ie, edge and maybe mobile chrome and safari. That should cover what we need.

From the packets I guess Automate would do fine. About 5 parallel would be enough I think (depending how often we want to run these).

**Comment by chrisprice** [comment]
Thanks, I've passed that on. Looking at the descriptions I opted for just the 1 parrallel as each comes with a different user which didn't sound like what we wanted. If it's wrong, I'll just get them to change it.

**Comment by bjedrzejewski** [comment]
Ok, looking forward to getting our hands on this!

**Comment by bjedrzejewski** [comment]
This is done in https://github.com/ScottLogic/d3fc/pull/626. What we still need from Chis / Coline is to encrypt BROWSERSTACK_USER and BROWSERSTACK_KEY (I can provide the values on Skype) as these won't work via pull request (Travis CI security).

**Comment by bjedrzejewski** [comment]
@ColinEberhardt I think we can close this one now

**Comment by ColinEberhardt** [comment]
Technical solution complete, see #656 for roll-out.

Thanks @bjedrzejewski :-)
