### ISSUE TITLE
Split between core and financial functionality

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/d3fc#572]
d3fc started out as a set of financial components but has become more generic over time. Currently it sits half way between generic charting and the more specialized financial charting. 

It would be great if we could highlight the core charting strengths without detracting from the more complex financial components the library provides, and vice-versa.

The proposal is to make acknowledge the dual purpose of the library by making it more explicit, splitting d3fc into d3fc-core and d3fc-finance. What this would mean in practice is:

 + Maintain a single project and website (for the purposes of keeping the logistics simple)
 + Redesign the website to make the split more evident (e.g. separate component lists, make financial an 'add on')
 + Determine which components live in each package
 + Update the build to spit out separate core and financial modules.

While we are at it, we should review where financial concepts have influenced our designs:

 + Having default x and y values of `date` and `close` does not make sense outside of finance.
 + Drop linear time series? It is an inflexible sub-set of the cartesian chart functionality

@ScottLogic/d3fc - any other thoughts?

**Comment by chrisprice** [comment]
I'm behind this, the finance side is a bit misleading of the concept.

linearTimeSeries should definitely go regardless of this proposal, it is a
narrow subset of cartesianChart.

However, changing default accessors is another good reason for the change.

I think it's important we keep it in one project for now. We don't have
enough test coverage and we're seeing bugs as it is. Moving things into
separate projects is only going to make that worse.

Maybe next step is to make that list of components which would move?
