### ISSUE TITLE
Layout visual test fails

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/d3fc#577]
http://localhost:8000/util/layout.html

> Uncaught TypeError: Cannot read property 'defaultView' 

At this line:

https://github.com/ScottLogic/d3fc/blob/7b71aec0223d850e5d4489ecb8dd18d4f6e4cedb/src/util/innerDimensions.js#L3

If we had #569 we could have picked this up via CI

**Comment by chrisprice** [comment]
That's passing for me @ 7b989c6715fc26e3e751ba085bd9a08651a7da58

**Comment by chrisprice** [comment]
(in chrome)

**Comment by chrisprice** [comment]
It was a bug in the tests, fixed in #581
