### ISSUE TITLE
Add a waterfall series type

### ISSUE THREAD

**Issue by jdunkerley** [ScottLogic/d3fc#591]
Very similar to a bar chart series type but bars start at the position of the last bar.

Main complication is that you would need to access the value of the previous point in the data series.

**Comment by chrisprice** [comment]
That sounds like it might be similar to a stacked bar?

**Comment by chrisprice** [comment]
FYI, @ColinEberhardt is [working on a refactor of those](https://github.com/ScottLogic/d3fc/pull/575) at the moment

**Comment by jdunkerley** [comment]
http://www.storytellingwithdata.com/blog/2011/11/waterfall-chart

Similar except need to have previous data point for next bar, where as stacked same point but different field I think?

**Comment by chrisprice** [comment]
Oh I see, would love to see an implementation :+1:

**Comment by bjedrzejewski** [comment]
I will have a go at the first implementation.

**Comment by bjedrzejewski** [comment]
@chrisprice and @jdunkerley what do you think about making a more general series type rather than waterfall? Something like a 'floating' bar chart or a range chart, not sure how you would call that - http://www.highcharts.com/demo/columnrange Waterfall is just a special case of this.

**Comment by ColinEberhardt** [comment]
Yes, I'd like to see the more general case implemented. However, I think this would have come naturally. Our series components are 'dumb' renderers, so in order to implement waterfall properly you would need a 'floating bar' series.

**Comment by chrisprice** [comment]
Is this not already supported by `fc.series.bar`?

**Comment by bjedrzejewski** [comment]
I will implement 'floating bar' series with a waterfall as an example.
