### ISSUE TITLE
fc.chart.cartesianChart should be renamed fc.chart.cartesian

### ISSUE THREAD

**Issue by chrisprice** [ScottLogic/d3fc#593]
... to be consistent.

**Comment by bjedrzejewski** [comment]
Are we not worried about breaking backward compatibility? Do we have any policy on changing names in this library?

**Comment by ColinEberhardt** [comment]
@bjedrzejewski - we are worried about backwards compatibility, this is why we use semantic versioning for our releases:

http://semver.org

Previous releases of the library are available on npm, cdnjs and GitHub.

This means we do not have to worry about changing our minds!

Although that doesn't mean we should just make breaking changes too often.
