### ISSUE TITLE
Rename layout-css attribute to layout-style

### ISSUE THREAD

**Issue by chrisprice** [ScottLogic/d3fc#596]
It's current name seems inconsistent with its purpose.

**Comment by chrisprice** [comment]
Also worth considering whether to change from camel-cased property names to dashes.

**Comment by bjedrzejewski** [comment]
Making pull request with the fix.

**Comment by bjedrzejewski** [comment]
Should be closed now.

**Comment by ColinEberhardt** [comment]
Thanks @bjedrzejewski 

Did you know you can [close issues via commit messages](https://help.github.com/articles/closing-issues-via-commit-messages/)?

**Comment by bjedrzejewski** [comment]
I did not know, thanks for the tip!
