### ISSUE TITLE
Create a well documented legend component

### ISSUE THREAD

**Issue by bjedrzejewski** [ScottLogic/d3fc#603]
I could not see a good legend component in the d3fc documentation. These are very useful and often dynamic (either changing depending on the data, or enabling user to toggle what can be seen in the diagram as in: http://www.primefaces.org/showcase/ui/chart/line.xhtml - click on the legend items).

Looking at the source of the project I can see legend.js but I am not yet entirely sure what to use it and what it gives. This issue is composed of two points:

1. Create a documentation for the existing legend component (if this is usable).
2. Add easy ways for users to add legend to the diagram. Good starting point would be making the legend that dynamically appears in http://d3fc.io/examples/low-barrel/ easier to integrate. The current code of the example has to bind directly into fc with <code>fc.tooltip = function()...</code>. This kind of tooltip could be a use case for a dynamic legend.

**Comment by ColinEberhardt** [comment]
It might help to look at the Yahoo Finance example to see twh legend in action:

**Comment by ColinEberhardt** [comment]
It might help to look at the Yahoo Finance example to see the legend in action:

http://d3fc.io/examples/yahoo-finance-chart/index.html

It is usable! Although it renders in HTML rather than SVG, which is not ideal in some contexts.

The Low Barrel example should really be using this legend, and yes, it does need documentation ;-)

**Comment by bjedrzejewski** [comment]
Great, thanks for pointing me to the yahoo example. I may quickly write some documentation on using the legend component, as it seems rather easy and useful.
