### ISSUE TITLE
Layout example on website fails

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/d3fc#610]
related to #577 ?

http://d3fc.io/components/layout/layout.html

**Comment by ColinEberhardt** [comment]
We need this: #569

**Comment by bjedrzejewski** [comment]
This seems like a horrible fix, but what we are getting from the website and from

```javascript
var layout = fc.layout();
d3.select('#layout-test').call(layout);
```

is [[node]], so we could potentially fix by:

```javascript
var layout = function(node) {
        try {
            node = node[0][0];
        }
        catch (err) {
            throw new Error('Arguments passed to fc.layout() should be of a type [[node]]. ' +
                'Original error: '+ err);
        }
        var dimensions = innerDimensions(node);
```

**Comment by chrisprice** [comment]
I recognise that problem, @colineberhardt changed the API a little while
ago. It should read -

```js

d3.select('#layout-test').layout();

```

**Comment by bjedrzejewski** [comment]
This works and is about 100 times simpler. I will make a pull request.

**Comment by bjedrzejewski** [comment]
@chrisprice this can be closed now. Thanks!
