### ISSUE TITLE
Computation of indicators is dependent on correct date order of data set

### ISSUE THREAD

**Issue by jdunkerley** [ScottLogic/d3fc#612]
If the original input is in descending order then the various indicators will compute their measures incorrectly.

Could possibly be fixed by adding an ordering function to the sliding window?

**Comment by chrisprice** [comment]
Do you think that's a reasonable assumption to make?

**Comment by jdunkerley** [comment]
Came up as we were testing with descending data on the Quandl feed.

Guess is reasonable to assume ascending sorted data.
