### ISSUE TITLE
Stochastic Oscillator example on the page is broken

### ISSUE THREAD

**Issue by bjedrzejewski** [ScottLogic/d3fc#614]
As you can see, the example for stochastic oscillator is broken:

http://d3fc.io/components/indicator/stochasticOscillator.html

**Comment by ColinEberhardt** [comment]
Another reason for implementing https://github.com/ScottLogic/d3fc/issues/569 !

**Comment by chrisprice** [comment]
This is caused by the rename done in response to the PR comments -

https://github.com/ScottLogic/d3fc/blob/master/src/indicator/renderer/stochasticOscillator.js#L13

We tend to refer to an instance of `mutliSeries` as `multi` but anything that isn't the same name as the import would work.

**Comment by chrisprice** [comment]
Actually I'm surprised this got through the linter, are we missing the relevant rule?

**Comment by chrisprice** [comment]
The [eslint playground](http://eslint.org/demo/) (`var foo = foo();`) doesn't pick this up either. Can whoever fixes this also create an eslint rule?

**Comment by bjedrzejewski** [comment]
Fixed, adding eslint will be good, can make another issue out of this one if we wish to track.
