### ISSUE TITLE
Remove css?

### ISSUE THREAD

**Issue by chrisprice** [ScottLogic/d3fc#635]

**Comment by ColinEberhardt** [comment]
Not convinced!

Before doing anything quite so drastic, I'd prefer to have a go at tidying up the CSS by coming up with some rules / conventions.

**Comment by chrisprice** [comment]
See the discussion on #629

**Comment by ColinEberhardt** [comment]
Should we close this issue? ;-)

**Comment by chrisprice** [comment]
Go on then
