### ISSUE TITLE
Adding Force Index to the indicators

### ISSUE THREAD

**Issue by bjedrzejewski** [ScottLogic/d3fc#638]
Another interesting indicators that we could easily add is a Force Index. Here are the details:

https://en.wikipedia.org/wiki/Force_index

**Comment by ColinEberhardt** [comment]
+1 to this

On Tue, Oct 20, 2015 at 2:10 p.m., ScottLogic/d3fc
<reply@reply.github.com>
wrote:
Another interesting indicators that we could easily add is a Force Index. Here
are the details:

[https://en.wikipedia.org/wiki/Force_index] https://en.wikipedia.org/wiki/Force_index
[https://en.wikipedia.org/wiki/Force_index]

**Comment by chrisprice** [comment]
I'd like to see this as well :+1:
