### ISSUE TITLE
Expand FC.Util.Extent to a component

### ISSUE THREAD

**Issue by jdunkerley** [ScottLogic/d3fc#646]
Thought it would be nice to have a little more flexibility with the Extent function.

If we created it as component could do something like:
```javascript
fc.util.extent()
    .includeZero()
    .scale(1.1)(data, ['high', low']);
```

**Comment by chrisprice** [comment]
Like it!

**Comment by ColinEberhardt** [comment]
I've wanted something similar ... on a few occasions I've found myself doing something like this:

```
fc.util.extent(series, function(d) { return 0; }, 'y')
```

(Notice you do not need to pass an array due to https://github.com/ScottLogic/d3fc/issues/468)

What if extent supported the following:

```
fc.util.extent(series, 0, 'y')
```

i.e. if a number is passed, convert to `function() { return number; }`

**Comment by jdunkerley** [comment]
passing a number would certainly cover the 0 case, guess felt we got a little more flexibility if we had a component model.

Could then do thing like roundTo(...)

**Comment by chrisprice** [comment]
I prefer the idea of a component over heavily overloaded method arguments. Maybe you could take a stab at the API for the component?

**Comment by jdunkerley** [comment]
yep happy to

**Comment by ColinEberhardt** [comment]
An API that allows for the addition of range padding would be useful.

**Comment by jdunkerley** [comment]
Think @owennw is going to have a go at creating this as first component for him.

**Comment by owennw** [comment]
I've implemented a function on extent that accepts a number and ensures that is it in the range, making the feature more flexible than just including 0. At the moment it's called "include".

What other features might we want on the extent? For example:

Scale(number): scales the max value up by the input, and the min value down by the same proportion? This wouldn't do anything to 0 though.

**Comment by jdunkerley** [comment]
I think scale should magnify the range around the average point.

**Comment by owennw** [comment]
How do we want `include` and `scale` to operate together?

For example:
Calculated range is `[10, 20]`, and `30` is included.
The scale is `0.8`.

Do we expect the final range to be `[11, 30]` or `[12, 28]` (or even anything else)?

**Comment by chrisprice** [comment]
I'd be careful using the word scale, it's quite a loaded term in d3. Is
there a good use case for scaling with a value < 1? Does that therefore
suggest a different name?

**Comment by ColinEberhardt** [comment]
I'd opt for something along the lines of padding or margin, basically a factor that increase the max and min by a given amount

**Comment by owennw** [comment]
I don't know if there's a good case for shrinking the range, but as it stands that certainly will be possible. Of course I could also reject inputs < 1.

Padding / margin have their own loaded terms too (despite my best efforts I always forget which is which, too). Would we rather have the min/max of the range increase by a fixed amount as input (e.g. `.padding(10)` would increase either side by either 5 or 10), or a more complicated function that 'scales' the range by a proportion (e.g. `.scale(1.2) increases the range by 10% on either end). Or both??

**Comment by jdunkerley** [comment]
I think we should only allow values greater than 0 for the to be names scale function.
I think it fits with trusting the program to allow 0 to 1 where they are trying to hide sections of the range.

Precedence-wise I would scale the range and then verify the included points are within the range. For example if we had include(0) would definitely want it even if shrank range.

Name-wise how about proportion?

**Comment by chrisprice** [comment]
There's quite a lot of precedence for this in d3's [ordinal scales](https://github.com/mbostock/d3/wiki/Ordinal-Scales), maybe it's worth looking over their API as well?

**Comment by jdunkerley** [comment]
ah, they call it padding through out.

**Comment by ColinEberhardt** [comment]
I was going to mention the same idea, do a bit of research. What term do other charting libraries use for this concept? I think 'padding' is quite a common term.

Also, regarding units, it would be great if we could allow for percent and 'domain' units. For example, `pad(100)` or `padPercent(0.1)`.

However, what happens if you include zero and apply a padding? things start to get complicated! Should this support asymmetrical padding?

**Comment by owennw** [comment]
Given they call it padding throughout I've implemented the function as `.pad(number)`, where currently the padding will occur, and then the included number is applied.

If desired percent and domain units pad functions can also be implemented -- perhaps in this issue. As for asymmetrical padding, maybe that's worth having a think about and implementing in a later issue?

**Comment by owennw** [comment]
Summary of discussion:
The `pad` function can be described by the following examples:
`[10, 20].pad(0) -> [10, 20]`
`[10, 20].pad(1) -> [5, 15]`

Whatever drops out of the calculation when pad accepts a negative number is okay.

**Comment by bjedrzejewski** [comment]
@jdunkerley can we close that?

**Comment by djmiley** [comment]
I have implemented asymmetrical padding in this function in d3fc-showcase. https://github.com/ScottLogic/d3fc-showcase/blob/develop/src/assets/js/util/domain/padYDomain.js

**Comment by djmiley** [comment]
When calling this with a padding percentage array such as [-0.1, 0.1], we shift the domain by 10%. Could/ should this be span out into a seperate call on `fc.util.extent()`, or can a user be trusted to figure this out for themselves?
