### ISSUE TITLE
Add browserstack testing to the main page and examples

### ISSUE THREAD

**Issue by bjedrzejewski** [ScottLogic/d3fc#656]
We should have tests checking for js error in these as well.

**Comment by chrisprice** [comment]
And visual tests!

**Comment by bjedrzejewski** [comment]
I wanted to make visualTests another issue as this requires a few changes in grunt- it need to be now:

run website, run website tests, stop website, run visualTests, run visualTests tests, end

**Comment by chrisprice** [comment]
Ok, feel free to spin that out.
