### ISSUE TITLE
Cartesian chart with the x and y axes crossing in the middle

### ISSUE THREAD

**Issue by bjedrzejewski** [ScottLogic/d3fc#666]
It seems that the current charts can't do a Cartesian chart with the x and y axis crossing in the middle.

If we can do that, there is no example on the website, so for example a chart like:

https://en.wikipedia.org/wiki/Political_compass

Is hard to make.

**Comment by ColinEberhardt** [comment]
We can do that :-D

Take a look at the bottom example for cartesian:

http://d3fc.io/components/chart/cartesianChart.html

This works quite elegantly, the axes are actually series (sounds crazy, but it works). Each axis has a baseline property which positions it with respect to the cross-axis. If a baseline is not set, it 'snaps' to the scale extents.
