### ISSUE TITLE
Add envelopes options to moving averages and EMA

### ISSUE THREAD

**Issue by bjedrzejewski** [ScottLogic/d3fc#678]
Envelopes are popular with moving averages and exponential moving averages. Example can be found here:

http://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:moving_average_envelopes

I think it should be easy to add support for drawing them on the chart.

**Comment by jdunkerley** [comment]
Can be done with an area series quite easily:

``` javascript
var env = fc.series.area()
    .y1Value(function(d) { return (d.movingAverage ? d.movingAverage * 1.025 : d.movingAverage); })
    .y0Value(function(d) { return d.movingAverage * 0.975; })
    .decorate(function(sel) { sel.enter().style('stroke-visiblity', 1); } );
```

**Comment by bjedrzejewski** [comment]
Great, could be a good addition to the website to show how this can be done.

**Comment by jdunkerley** [comment]
one little thing I found when plugging together was needing to cope with undefined in y1value to make it plot

**Comment by ColinEberhardt** [comment]
> one little thing I found when plugging together was needing to cope with undefined in y1value to make it plot

if the logic were applied to the data, i.e. adding upper / lower values, rather than being within the accessors, would that solve the problem.

**Comment by ColinEberhardt** [comment]
(hit close by mistake!)

**Comment by bjedrzejewski** [comment]
The value needs to be computed on the actual EMA (by adjusting it) as with being exponential it provides some mathematical challenges.

**Comment by jdunkerley** [comment]
It is just a percentage scale up and down of the (S/E)MA result.

Problem I had was `undefined * 1.025` is `NaN`. Guess Colin's suggestion is that if we had it as part of the indicator then we could add as part of computation which would hence be trivial to leave as undefined at that part.

**Comment by jdunkerley** [comment]
Having played a little I guess I would say we could do something like:

``` javascript
var envCalc = fc.indicator.algorithm.envelope()
  .size(0.025)
  .midValue(function(d) { return d.movingAverage; });
```

The `envelope` would add an upper and lower point to the series.

We could then create and envelope render which could be shared with the bollinger indicator as well. Effectively plotting a faded `area` chart with an upper, lower (and mid?) series within a `multi` series.

Tried it out as [JSBin](https://jsbin.com/darigu/4/edit?html,js,output)

**Comment by bjedrzejewski** [comment]
I think it is a good idea, the envelope seems like a rather generic construct that could be applied to any series.

**Comment by ColinEberhardt** [comment]
Looks good @jdunkerley

**Comment by bjedrzejewski** [comment]
I am implementing it now as a separate indicator based on @jdunkerley idea.
