### ISSUE TITLE
Make it obvious that the d3-financial-components package is old

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/d3fc#679]
The information here should clearly sign-post d3fc: 

https://www.npmjs.com/package/d3-financial-components

**Comment by chrisprice** [comment]
I'm pretty sure you get a deprecation notice when you install it (or at
least I set that up for a project which I think was this one)

**Comment by ColinEberhardt** [comment]
Yes, pretty sure I've seen that. I was planning on adding a notice to the README for the project.

**Comment by chrisprice** [comment]
Assuming this is no longer a problem.
