### ISSUE TITLE
Support different point 'shapes'

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/d3fc#680]
This is a pretty standard chart feature:

![](http://helpcentral.componentone.com/NetHelp/SpreadNet8/WF/artwork/plottypes-y-spoint.png)

if the circle rendering logic of our current point series were moved into `fc.svg.circle`, this could be made pluggable, so that other point types could be implemented.

**Comment by jdunkerley** [comment]
Was going to suggest something similar myself. 

Wondered whether we could do by providing decorators on a base point series which just created the `g` node.

**Comment by jleft** [comment]
[`d3.svg.symbol()`](https://github.com/mbostock/d3/wiki/SVG-Shapes#symbol) might be useful.

**Comment by ColinEberhardt** [comment]
Thanks for the heads-up @jleft - looks like this could be exactly what we need.

**Comment by bjedrzejewski** [comment]
I will work on this today. @jleft thanks for the tip!

**Comment by jleft** [comment]
No worries! :smiley:
