### ISSUE TITLE
components/series/grouped-bar.html is broken

### ISSUE THREAD

**Issue by bjedrzejewski** [ScottLogic/d3fc#687]
components/series/grouped-bar.html is broken, possibly due to an issue in groupedBar.js.

This is breaking the build.

**Comment by bjedrzejewski** [comment]
@owennw @ColinEberhardt It seems like the issue was caused by merging the new 'extent' and 'small multiples' among other things. Stacked.md looks bad (have a look) and grouped-bar.md is not working. Any hints are welcome.

**Comment by bjedrzejewski** [comment]
I think I got it, will push fix soon.

**Comment by ColinEberhardt** [comment]
Great - thanks
