### ISSUE TITLE
Add Elder Ray Indicator

### ISSUE THREAD

**Issue by bjedrzejewski** [ScottLogic/d3fc#690]
Elder Ray is an indicator that features in Trading for a Living by Alexander Elder (very popular book) and is defined as two separate indicators:

Bull Power = Daily High - n-period EMA
Bear Power = Daily Low - n-period EMA 

With default 13 days period (customisable) and has an interesting visualization as two bar series:

http://www.dailyfx.com/forex_forum/attachments/coding-strategy-advisors-indicators-functions/65921d1283304973-elder-ray-bear-bull-power-20100831-m12-194kb.jpg

**Comment by ColinEberhardt** [comment]
This would be a useful addition - thanks.
