### ISSUE TITLE
Rendering a cartesian chart without data results in an error

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/d3fc#697]
JS:

```
    var chart = fc.chart.cartesian(
                  d3.scale.linear(),
                  d3.scale.linear());

    d3.select('#scatter-chart').call(chart);
```

HTML: 

```
<svg id='scatter-chart' style='width: 600px; height: 400px'></svg>
```

This yields the following error:

```
caught TypeError: Cannot read property 'length' of undefined
```

This is basically an open ended question, should this result in an error? is there much sense in a chart without data? And if so, what would we have to change to make this work without error? does it have an impact on all the various series implementations?

**Comment by chrisprice** [comment]
So the following doesn't produce an error - 

```js
var chart = fc.chart.cartesian(
                  d3.scale.linear(),
                  d3.scale.linear());

    d3.select('#chart').datum([]).call(chart);
```

![image](https://cloud.githubusercontent.com/assets/433457/10864301/607fdd04-7fe1-11e5-970a-278a2485074a.png)


(intentionally gratuitous use of playground :smile: )

**Comment by chrisprice** [comment]
I think our components should assume a valid selection bound to appropriately shaped data when they are invoked. Adding handling for the error cases is going to complicate the components. 

Conversely, I've watched people get very confused trying to use our components. Although I think that's more of a d3 problem than anything specific to d3fc.

It probably comes back to who we're targeting with the library, are they proficient d3 users or people just looking to configure a chart?

**Comment by chrisprice** [comment]
Unusually, I agree with myself from 9 month ago 😄
