### ISSUE TITLE
Add step series chart

### ISSUE THREAD

**Issue by bjedrzejewski** [ScottLogic/d3fc#698]
In the d3fc vision there is a mention of step series. It looks like that:

http://www.highcharts.com/stock/demo/step-line

It is getting more popular and I have seen it in some of our designs. I think it should be very similar to line series, just rendered differently, so maybe a different renderer is what is needed.

**Comment by bjedrzejewski** [comment]
I will work on implementing it, if no one objects.

**Comment by jleft** [comment]
Not 100% sure if this is the same, but I think this can already be achieved using [interpolate()](https://github.com/ScottLogic/d3fc/blob/56278921b990ff975663f675d3487113336f2a46/src/series/line.js#L43) on the line series?

```js
fc.series.line()
    .interpolate('step');
```

**Comment by bjedrzejewski** [comment]
@jleft wow... I will just add it as an example to the website then! It is exactly that.
