### ISSUE TITLE
Adding Box Plot series

### ISSUE THREAD

**Issue by bjedrzejewski** [ScottLogic/d3fc#701]
This is a series popular among statisticians and different scientists:

https://en.wikipedia.org/wiki/Box_plot

I believe that we should support it (as we support candlesticks and other specialized series).

**Comment by bjedrzejewski** [comment]
I will take this feature

**Comment by bjedrzejewski** [comment]
![image](https://cloud.githubusercontent.com/assets/9947570/11471270/18572e64-975c-11e5-85e7-1b48791c9797.png)

**Comment by chrisprice** [comment]
Added in e743e0f70ddf6730dc8edc29ed730710ca2e33d8
