### ISSUE TITLE
IDEA: Support resizing

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/d3fc#704]
I've been thinking about how to support windows resizing with d3fc and have come up with a potential solution.

My idea is to extent d3 selection to add an `onResize` method that takes a single callback. This method handles the browser resize event, inspecting each of the elements within the selection to see if their size has changed. When this occurs the callback is invoked. You can use it as follows:

```
d3.select('#chart').onResize(renderChart);
```

You can see it in action here:

https://jsbin.com/lihecunahu/edit?js,console,output

It would be great if you could actually make any 'pipeline' of d3 selection operations re-evaluate on browser resize. For example:

```
  d3.select('#chart')
      .datum(data)
      .resize()     // ensures that this 'pipeline' is re-evaluated when the browser is re-sized.
      .call(chart);
```

However, I don't think this is possible with the way selections are implemented. If they were lazy-evaluated this might work.

What do others think?

relates to #681

**Comment by bjedrzejewski** [comment]
One of the principles of rendering in d3fc is the full redrawing on change for simplicity (according to our manifesto). Based on that, full redrawing of the component when re-sizing should be something that we can implement on this pipeline. May need to cache some values though... At least thats my guess so far.

**Comment by ColinEberhardt** [comment]
The problem is d3 selection methods apply their logic to the current selection, causing the DOM state to mutate, then pass the selection to the next method.

With the following code all `resize` will have visibility of is that it has been passed a selection with a certain state:
```
  d3.select('#chart')
      .datum(data)
      .resize()     // ensures that this 'pipeline' is re-evaluated when the browser is re-sized.
      .call(chart);
```
It has no idea what steps caused it to reach that state, or what steps follow.

I just can't see a way to make it work.

**Comment by bjedrzejewski** [comment]
Maybe we need a `.resize()` that wraps around everything and on resize, simply re-renders the whole chart?

**Comment by chrisprice** [comment]
I'm not sure about adding something to the selection prototype, I think there are too many different ways you might want to render. How about a flag on fc.util.render?

**Comment by ColinEberhardt** [comment]
What I would want from this component or function is a way to invoke a callback (my render function) whenever the size of the element I am rendering to changes.

I'm not sure how to use `fc.util.render` for this? Are you considering replacing rAF with a resize event handler so that you could queue up a callback to execute when the window resizes?

**Comment by chrisprice** [comment]
If you are responding to resize events you'll still want the rAF throttle
for performance. I'm not sure that optionally resizing based on measuring
is that much of a performance win. Also it's the only place in our codebase
with a concept of rendering so feels like the natural place to hook into
resizing.

Maybe there's some way of moving render to the selection prototype (as an
optimised call with auto resizing invocation) although I'm not sure how you
deal with idempotentcy in that case...

**Comment by ColinEberhardt** [comment]
If it isn't much of a performance win, then having a very thin wrapper around the window resize event is probably all we need, and I agree  `fc.util.render` is a good place to add this logic.
