### ISSUE TITLE
Add a recreation of "The Wealth & Health of Nations" (with transitions and interaction) to the website

### ISSUE THREAD

**Issue by jleft** [ScottLogic/d3fc#718]
Add a recreation of [Mike Bostock's recreation](http://bost.ocks.org/mike/nations/) of Gapminder’s [Wealth & Health of Nations](http://www.gapminder.org/world/).

~~Current work in progress: http://jleft.github.io/wealth-and-health-of-nations/~~

---

(Thought I'd add an issue in case someone was working on something similar.)

**Comment by ColinEberhardt** [comment]
I did add a very simple example using the same data to illustrate a bubble chart here:

http://d3fc.io/examples/bubble/

However, I'd really like to include your more interactive example.

**Comment by jleft** [comment]
Great, sounds good. There's a few more things I'd like to do, then I think I'll be fairly happy it with and ready to put up a PR.

+ [ ] Add axis labels
+ [ ] Update to d3fc 3.x.x -> 4.x.x
+ [ ] Investigate performance
