### ISSUE TITLE
Allow extent to support symmetrical domains

### ISSUE THREAD

**Issue by owennw** [ScottLogic/d3fc#728]
fc.util.extent could support symmetrical domains, centered around a point with the range either set or computed somehow from the data.

**Comment by owennw** [comment]
First thoughts:

- Add a new function to extent, perhaps called `about(input)` that accepts an input, and uses that value as the centre point about which to create the range.
- The calculated range would be relative to this point, and then extended symmetrically in both directions using the max value calculated.

So if, for example, the data were shaped in such a way to have produced a range of `[6,  13]` then the product of modifying the extent would be:
`.about(9)` -> `[5, 13]`
`.about(5)` -> [-3, 13]

How does that sound?

**Comment by ColinEberhardt** [comment]
Sounds spot on - the only think I am not sure about is the name. How about one of the following:

 + `symmetricalAround()`
 + `symmetric`
 + `symmetry`

**Comment by owennw** [comment]
Given that this will be the interface the natural question is how will this play with the other properties, specifically `pad` and `include`?

In my opinion `symmetricalAround()` should occur before both the `pad` and the `include`.

**Comment by ColinEberhardt** [comment]
I think so, yes - although hard to say without trying it out against a few use cases.

**Comment by djmiley** [comment]
Does this work correctly with dates? When calling on `fc.util.extent().fields('date').symmetricalAbout(new Date(345345350000))(data);` , my output is `[-757805300000, "Thu Dec 11 1980 01:15:50 GMT+0000 (GMT Standard Time)1103150650000"]`.

Whereas when calling on `fc.util.extent().fields('date').symmetricalAbout(345345350000)(data);`, my output is `[-757805300000, 1448496000000]`

**Comment by djmiley** [comment]
I've looked in https://github.com/ScottLogic/d3fc/blob/master/tests/util/extentsSpec.js and it only makes the promise that it should pad dates. 

Include works though, but probably need some tests on this regard.
