### ISSUE TITLE
A lot of the code within the website is not linted

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/d3fc#730]

**Comment by owennw** [comment]
Do we want to use something like https://github.com/wooorm/eslint-md ?

**Comment by ColinEberhardt** [comment]
I doubt that would work as our code is within the front matter rather than code blocks embedded within markdown.

**Comment by jdunkerley** [comment]
next step for playground is to move the JS to files to try and get us back to one pass Assemble again. That would make linting easy as well
