### ISSUE TITLE
Random data generator can return undefined values

### ISSUE THREAD

**Issue by chrisprice** [ScottLogic/d3fc#731]
Using the default values, when asked for a single value the generator can return undefined due to the post filtering. Is this appropriate?

**Comment by ColinEberhardt** [comment]
No it isn't!

Also, the post filtering often means that it doesn't necessarily return the number of points you asked for, e.g.

```
fc.data.random.financial()(5).length === 3
```

This confuses me!

**Comment by owennw** [comment]
I'll look at this

**Comment by owennw** [comment]
I've submitted this PR under the assumption that if a number of values are requested but with a given filter are all subsequently filtered out it is okay to return `undefined` / nothing.

As it is, with no filter `undefined` should never be returned.
