### ISSUE TITLE
Move scale calculation on Elder Ray and Stochastic Indicators into the Renderer

### ISSUE THREAD

**Issue by owennw** [ScottLogic/d3fc#734]
The `yScale` on the stochastic indicator will always be `[0, 100]`, so there is no need to force the user to specify this.

Similarly in the Elder Ray indicator to find the range one would have to dig deep into the objects -- instead it could be calculated in the renderer.

**Comment by ColinEberhardt** [comment]
> The yScale on the stochastic indicator will always be [0, 100], so there is no need to force the user to specify this.

This is true, but not sure how to do this without introducing coupling? I'm happy to review suggestions.

> Similarly in the Elder Ray indicator to find the range one would have to dig deep into the objects -- instead it could be calculated in the renderer.

Isn't Elder extent something like this ...

```
var extent = fc.util.extent
        .fields([function(d) { return d.elder.bullPower; }, function(d) { return d.elder.bearPower; }])
        .symmetricAbout(0);
```

That doesn't look too bad to me.

We are banking on ES6 turning this into:

```
var extent = fc.util.extent
        .fields(d => d.elder.bullPower, d => elder.bearPower)
        .symmetricAbout(0);
```

thanks to arrow functions and rest parameters.

**Comment by owennw** [comment]
I think the Elder Ray indicator has been sorted. The remaining question is, generally, if an indicator's range is always going to be the same do we want to incorporate that into the indicator/renderer to save the users boilerplate code?

**Comment by ColinEberhardt** [comment]
> The remaining question is, generally, if an indicator's range is always going to be the same do we want to incorporate that into the indicator/renderer to save the users boilerplate code?

How would you propose doing that? The renderers do not 'own' the scale, where this range would be applied, so I am not sure how this could be achieved (without destroying our separation of concerns)

I'd be happy to see a suggested implementation!

**Comment by owennw** [comment]
I'm not sure it can be achieved to be honest. At the moment I have no ideas on how to implement it cleanly, anyway.
