### ISSUE TITLE
Document (or fix) the conflict in catesian chart with Bootstrap's SVG overflow rule

### ISSUE THREAD

**Issue by chrisprice** [ScottLogic/d3fc#737]
As bootstrap is so prevalent and the issue basically makes it look like the charts are broken, I think we should be more proactive in fixing this.

**Comment by ColinEberhardt** [comment]
Good point - do you know why bootstrap has that particular rule?

**Comment by chrisprice** [comment]
It appears to come from [this commit](https://github.com/necolas/normalize.css/commit/8cece826593d0219d53f9e666d9f4f95368fdc3a) (in another project which bootstrap copy/pastes)
