### ISSUE TITLE
Improve Playground's method of mapping supplemental files

### ISSUE THREAD

**Issue by jdunkerley** [ScottLogic/d3fc#757]
At the moment the playground does this but pattern matching the 'data. but can be done with Assemble variables.

Perhaps something like a relativePath variable in YAML.

**Comment by owennw** [comment]
I'm not sure what the first sentence means..

**Comment by chrisprice** [comment]
Fixed (in a manner of speaking) by 2bf4206de72876ee4b4044f2ae88f691c54400eb
