### ISSUE TITLE
Tidy fc.data.random.financial

### ISSUE THREAD

**Issue by owennw** [ScottLogic/d3fc#763]
This component is a bit messy, and required a refactor.

1. The `calculateInterval` performs date manipulation using a `millisecondsPerYear` magic number.

2. The component mutates the `startPrice`,  `startDate` and `startVolume` properties as it is executed.

3. There are many properties that are not documented, for example the `mu` and `sigma` properties.

This list is not exhaustive.

**Comment by ColinEberhardt** [comment]
I'd combine this with #754 - basically reimplement the component, rather than just try to fix up the current implementation.

**Comment by ColinEberhardt** [comment]
At the same time I think it's worth looking at the API that this component exposes. Currently you ask it to give you 'n' points from a specified start date. For most charts what you actually want is to generate data for a pre-determined data range at a specific period, e.g. 3 months @ 1day, 1day @ 5 mins.

However, we also need to be able to stream new data into a chart, which would require a different interface. Should a streaming interface be stateful?

Probably worth asking @chrisprice for his opinions on the interface also.

**Comment by chrisprice** [comment]
For stateful functionality I'd like to see something like -

```js
var generator = fc.data.random.financial()
  .start(new Date())
  .interval(d3.time.minute);

generator(new Date() + 1d); // [{ date: now, ... }, { date: now+1m, ... }]

var stream = generator.stream();

stream(); // { date: now, ... } 
stream(); // { date: now+1m, ... }
```

**Comment by owennw** [comment]
Does that mean removing the ability to specify the number of points completely, in favour of setting a period and duration, and letting however many points that amounts to fall out?

**Comment by ColinEberhardt** [comment]
> Does that mean removing the ability to specify the number of points completely, in favour of setting a period and duration, and letting however many points that amounts to fall out?

I'd say so, yes. I think it is an API that s a better reflection of how the component would be used.
