### ISSUE TITLE
Low Barrel Example from Website Data?

### ISSUE THREAD

**Issue by rymdluo** [ScottLogic/d3fc#764]
I am trying to adopt the low barrel example into my own presentation, except with a line chart instead of OHLC, similar to svg:navigator and using .csv to import data.

However, I am having quite a bit of trouble understanding the initial code- I have only been exposed to adopting data from .csv, .tsv and json so far. 

Am I correct to think that the "<path d= M..." portion of the data is in fact the data that you are deriving all the information from? If so how does it do this? Would be helpful for me to see where I can place my d3.csv codes.

Further, would you have any advice on how to implement line chart with the legend and tracking cursor without any hiccups? I am looking at the navigator for reference since it is already a line chart.

**Comment by rymdluo** [comment]
I slept on this and figured out what was wrong with my own understanding of the data portion, the data is randomly generated so I had to remove all the innards past the <svg class="main/volume/navigator"> elements to function as intended and it is so far.

Will update again as I try to replace the OHLC with a line chart!

**Comment by ColinEberhardt** [comment]
Hi @rymdluo glad to hear you've managed to work things out - the low-barrel example probably has quite a few elements that you will not need for a simpler line chart. I'll see if I can quickly throw something together for you ...

**Comment by rymdluo** [comment]
Hey @ColinEberhardt I would greatly appreciate the help!

**Comment by ColinEberhardt** [comment]
No problem - here's a greatly simplified version of the code that renders weather data from CSV rather than artificially generated financial data:

http://bl.ocks.org/colineberhardt/000b1721b69868f1ce5d

This is still a little more complicated than I would like it to be - mostly because we do not have a tooltip component in d3fc yet. I'm also considering adding a 'navigator' component which would wrap up a chart together with the d3 brush - making this sort of example a little easier to assemble.

Anyhow, hope that helps.

**Comment by rymdluo** [comment]
Hey @ColinEberhardt, cheers! It was tremendously useful for me. 

Btw I faced a similar issue at #766 too.

**Comment by chardt17** [comment]
@ColinEberhardt (nice last name) Actually I was wondering if you could share the data file for your simpler example. Ultimately I'm trying to re-create weather underground's charts like this: http://www.wunderground.com/us/wa/tacoma/zmw:98406.1.99999? . What I want to add to the chart is air pollution readings so you can follow along pollution and wind speed and direction for Beijing. I'm new to javascript, so it might be very basic, but I would appreciate it if I could see your csv file as I try to adapt for my own purposes.

**Comment by rymdluo** [comment]
Hi @enviroeberhardt 

You would be able to grab the .csv from the source that @ColinEberhardt is using: http://bl.ocks.org/ColinEberhardt/raw/000b1721b69868f1ce5d/fac25d370bbdc4b7a4cf713656db5476ffa791f6/downsample.csv

In future, if you need to do some reverse analysis you can always inspect the example (right click on page, click inspect) and in this instance, grab the link to the .csv from the 'network' tab (assuming you are using chrome). You would be able to view the full javascript in this manner too.

Good luck!
