### ISSUE TITLE
Cartesian chart axis labels are ordered before plot area

### ISSUE THREAD

**Issue by jleft** [ScottLogic/d3fc#766]
The [axis labels in cartesian chart](https://github.com/ScottLogic/d3fc/blob/master/src/chart/cartesian.js#L74-L83) are ordered before the plot area. If the labels were positioned to be in the same space as the plot area, they would be obscured by the background rect element (and any other element in the plot area).

I can't see a case where the labels should be under the plot area. I'd suggest re-ordering the element, so the labels appear above the plot area.

**Comment by ColinEberhardt** [comment]
Good point, yes, I'd consider that to be a bug. Just FYI we've discussed cartesian element z-order before here #671
