### ISSUE TITLE
Could be easier to style crosshair

### ISSUE THREAD

**Issue by jleft** [ScottLogic/d3fc#767]
The crosshair doesn't add any classes to help select its child elements - the vertical and horizontal line annotations are particularly hard to differentiate.

It would be nice if classes were added to help select the relevant elements (possibly in a way similar to the indicator renderers).

Potentially a separate issue, but a potential solution, is that the annotation component doesn't add a class to indicate its orientation - maybe that's something it could do?

---

My use case is that I'd like to hide the horizontal line. Would be good if something like this would work:

```css
.crosshair > .horizontal {
  visibility: hidden;
}
```

**Comment by ColinEberhardt** [comment]
I like your suggested solution - see the above PR.
