### ISSUE TITLE
Browserstack logo is not visible on the bottom of the website

### ISSUE THREAD

**Issue by bjedrzejewski** [ScottLogic/d3fc#776]
It just gives you a white rectangle rather than the icon.

Here:

http://scottlogic.github.io/d3fc/

**Comment by chrisprice** [comment]
I'd spotted this happening sometimes but hadn't pinned it down. Looks like the relative path is wrong, I'm sure there's a way to get less to fix that....

**Comment by chrisprice** [comment]
This appears to be fixed by the custom domain.
