### ISSUE TITLE
Growing chart issue

### ISSUE THREAD

**Issue by chrisprice** [ScottLogic/d3fc#779]
Arnaud threw together the following example of a chart which keeps growing vertically -

http://jsbin.com/deqema/edit?html,js,output

I'm not sure if there's anything we can/should do to fix this, as it relates to `svg` element's default `inline` display but it might be possible to do something in `innerDimensions`?

@ColinEberhardt

**Comment by Afredon** [comment]
A warning in documentation could be enough, but that would help :)

**Comment by chrisprice** [comment]
Another option would appear to be setting the `vertical-align` of the `svg` element -

http://jsbin.com/keyiboqitu/edit?html,css,output

**Comment by chrisprice** [comment]
After discussion, setting the `vertical-align` to `middle` would seem to be the best of a bad set of fixes. The main priority was to not change the `display` to `block` for fear of breaking integration with frameworks like e.g. bootstrap.

**Comment by ColinEberhardt** [comment]
See the transitions example in a codepen to reproduce: https://d3fc.io/components/introduction/3-transitions.html

**Comment by ColinEberhardt** [comment]
See also: http://stackoverflow.com/questions/25248203/vertical-align-middle-reducing-height-of-parent-container
