### ISSUE TITLE
extent - handling of undefined values

### ISSUE THREAD

**Issue by chrisprice** [ScottLogic/d3fc#812]
If I use extent to try and calculate the domain of a macd generated using the built-in algorithms it generates an illogical result because of the leading undefined values.

**Comment by ColinEberhardt** [comment]
I guess it should just ignore undefined values?

**Comment by chrisprice** [comment]
Actually I'm less sure about this, I think a bug in my code was confusing me. If this was the case then the [MACD playground](http://d3fc.io/playground/playground.html?example=components/indicator/macd) example shouldn't work...

**Comment by chrisprice** [comment]
Yea it was a bug in my code.
