### ISSUE TITLE
Volume chart with negative values

### ISSUE THREAD

**Issue by zeleniy** [ScottLogic/d3fc#820]
Guys is it possible to apply negative values to volume chart (and navigation chart) in this example http://scottlogic.github.io/d3fc/examples/low-barrel/? It works incorrect with negative values... and by the way - does any d3fc forum exists?

**Comment by ColinEberhardt** [comment]
The volume chart in that example uses the [bar series component](http://d3fc.io/components/series/bar.html), which does support negative values. Here's a quick example:

https://jsbin.com/buhuzetoja/edit?html,js,output

Can you share an example which shows the issue you are having? 

No, we don't have a forum - but feel free to ask anything you like via GitHub issues.

**Comment by zeleniy** [comment]
Super! Here is an example - http://zeleniy.bitbucket.org/
My client would like to have to "Low Barrel" charts on the single page, but second should support volume chart with negative values. And as consequence navigation chart should support negative values too.

I have modified original code from "Low Barrel" [example page](http://d3fc.io/examples/low-barrel/index.html) and rewrite it in OOP style.
So when i create first chart i just supply data set to the chart constructor. For the second chart i use the same data set but randomly change values to negative state.
```<script>
var chart1 = new StockChart(chartData).render("#chart1");
chartData2 = chartData.map(function(d) {
    if (Math.random() > 0.5) {
        d.v = - d.v;
    }
    return d;
})
var chart2 = new StockChart(chartData2).render("#chart2");
</script>```

**Comment by ColinEberhardt** [comment]
I'm in my mobile at the moment, so cannot take a look at the code - I'll take a look later today. I think that should be simple to fix, looks like you just need to set a baseline of zero.

**Comment by zeleniy** [comment]
Thank you for the idea! I fixed it - http://zeleniy.bitbucket.org/ - and second chart now support negative values. Now i will try to apply negative values to navigation chart.

**Comment by zeleniy** [comment]
Ok, i have done it! Thank you!
