### ISSUE TITLE
How to set parameter in MovingAverage and exponentialMovingAverage?

### ISSUE THREAD

**Issue by qvantor** [ScottLogic/d3fc#828]
How to set indicator parameters for control smoothing on line?

**Comment by ColinEberhardt** [comment]
You can use the `windowSize` property on moving average (and other indicators) to determine the amount of smoothing applied.

**Comment by qvantor** [comment]
I think better way add opportunity to set parameter.

**Comment by qvantor** [comment]
Because change windowSize it not good practice, I guess

**Comment by chrisprice** [comment]
I'm not sure what your trying to achieve nor why you consider changing `windowSize` to be an anti-pattern. Please could you provide a code example or a clearer description?

**Comment by chrisprice** [comment]
Closing due to lack of repsonse, please open a new issue if you are still having problems.
