### ISSUE TITLE
Add plot-area-overlay to cartesian chart with overflow visible

### ISSUE THREAD

**Issue by chrisprice** [ScottLogic/d3fc#831]
I've come across many use-cases where I would like to permit overflow of some components within the plot area but not others e.g. hidden for series, visible for decorated line annotations. I would propose adding a new plot-area located on top of the existing one with exactly the same API.

**Comment by ColinEberhardt** [comment]
With our d3v4 we will no longer have a cartesian chart - see https://github.com/d3fc/d3fc-element instead.
