### ISSUE TITLE
Default implementation for the point series obscures some of the first and last points

### ISSUE THREAD

**Issue by owennw** [ScottLogic/d3fc#834]

**Comment by ColinEberhardt** [comment]
@owennw - I'm not sure what this issue actually means. Can you add a screenshot or link to a fiddle that highlights the issue?

**Comment by owennw** [comment]
![point_obscured](https://cloud.githubusercontent.com/assets/14889759/12289625/8123b3b4-b9d4-11e5-925d-ccbdda7f14fb.PNG)

Attached.

**Comment by owennw** [comment]
The first and last points are not fully shown.

**Comment by ColinEberhardt** [comment]
That's not actually an issue ;-)

In practice you should pad your axis domain using `fc.util.extent` to accommodate the fact that points circles rather than, erm ... points.
