### ISSUE TITLE
use modified d3.zip to avoid additional traversal

### ISSUE THREAD

**Issue by rrag** [ScottLogic/d3fc#837]
Love this library. Great work. I learned how to use d3 style functions by looking at the source of the different calculators

I have shamelessly copied some of the calculators to my own [project](https://github.com/rrag/react-stockcharts).

While testing and looking closer at the source I identified there is an opportunity to use a [modified version](https://github.com/rrag/react-stockcharts/blob/next/src/lib/indicator/calculator/zipper.js) of `d3.zip` and avoid an [additional](https://github.com/ScottLogic/d3fc/blob/7524b787ca60b0a83cf0fa25a6db1d4a88259762/src/indicator/algorithm/merge.js#L13-L14) [array](https://github.com/ScottLogic/d3fc/blob/42f1ceb1ec9381d7f9ea683eed4749ee5c0d1f1c/src/indicator/algorithm/calculator/macd.js#L26-L27) [traversal](https://github.com/ScottLogic/d3fc/blob/42f1ceb1ec9381d7f9ea683eed4749ee5c0d1f1c/src/indicator/algorithm/calculator/macd.js#L37-L38).

Look at this in action [here](https://github.com/rrag/react-stockcharts/blob/next/src/lib/indicator/calculator/macd.js#L60-L61) and [here](https://github.com/rrag/react-stockcharts/blob/next/src/lib/indicator/calculator/sto.js#L71-L72)

I send PR to implement these if you so wish.

**Comment by ColinEberhardt** [comment]
Glad to hear you like d3fc and have found it useful. Regarding the indicators / calculators, is there any way you could depend directly on our components? They [have been wrong in the past](https://github.com/ScottLogic/d3fc/pull/830), so would make maintenance easier.

A PR with improvements would be great - thanks.

**Comment by rrag** [comment]
I was of the same idea, about depending on them instead of copying and modifying the source code. There are some small changes I will need, for e.g. 

- some of the windowSize attributes are [hard](https://github.com/ScottLogic/d3fc/blob/master/src/indicator/algorithm/calculator/stochasticOscillator.js#L12) [coded](https://github.com/ScottLogic/d3fc/blob/master/src/indicator/algorithm/calculator/macd.js#L13), and does not accept input
- Stochastic oscillator does not allow for smoothing of `K` to support Full STO
- bollingerBands always use sma and no option to use ema

and a few more reasons I decided to copy them instead. My library already supports these options above and I don't want to remove them. If these calculators can be updated to support both our needs then certainly I prefer to depend on these instead of copying them over.

Would you be willing to create a separate repo and npm package for just these indicators and calculators? I would not want to include the other portions like the renderer. I can contribute to make this new repo suitable for me. and both the libraries depend on this new package. Thoughts?

**Comment by ColinEberhardt** [comment]
Actually, `windowSize` is [exposed via a modified version of `d3.rebind`](https://github.com/ScottLogic/d3fc/blob/master/src/indicator/algorithm/calculator/stochasticOscillator.js#L59), becoming `kWindowSize` on the parent component.

Anyhow, I am all for the idea of moving the calculators to a separate repo. They do not have any dependency on D3 so would sit quite nicely on their own. I'll see what I can do ...

**Comment by rrag** [comment]
ah, I see. sorry did not even scroll down that far. I will work on the PR for an improved zip and ATR over the next week.

**Comment by chrisprice** [comment]
The indicators are now in their [own repository](https://github.com/d3fc/d3fc-technical-indicator/) and are independent of the calculators (which are still part of this repo). I hope this makes them easier to use.

**Comment by ColinEberhardt** [comment]
@rrag - would you be interested in integrating the [d3fc-technical-indicators](https://github.com/d3fc/d3fc-technical-indicator/) project into your react stock chart project? It would be good to include some of the indicators you have added as well.

**Comment by rrag** [comment]
@ColinEberhardt absolutely I will begin to break it out soon

**Comment by ColinEberhardt** [comment]
That's great news @rrag - if you need any help, give me a shout
