### ISSUE TITLE
Unexpected candlestick width

### ISSUE THREAD

**Issue by Dividuals** [ScottLogic/d3fc#863]
When i call candlestick series with data spaced by 4 hours, il get this result :

![capture d ecran 4](https://cloud.githubusercontent.com/assets/9746417/12806903/817ba5d2-cb0a-11e5-9f8d-12620f6793bc.png)

Instead of :

![capture d ecran 3](https://cloud.githubusercontent.com/assets/9746417/12806906/8cf225bc-cb0a-11e5-8665-4d51063f9547.png)

When i move on x axis (Date), it apear sometimes in the correct width.

I don't use any discontinuity provider.
When i use the "skipWeekends" example, this behavior apear only on candlestick series spaced by 1 day.

EDIT: After changing the number of candlestick rendered (500 before, 100 now), width is back to normal for 4h spaced series. But it now apear sometimes on all series. It seems to be caused by x scale domain ...

**Comment by ColinEberhardt** [comment]
The candlestick series automatically computes the width based on the data, as you can see here:

https://github.com/ScottLogic/d3fc/blob/master/src/series/ohlcBase.js#L14

The `fractionalBarWidth` function finds the smallest distance between points along the x-axis, then returns a width as a fraction of this distance. My guess is that somewhere among your data you have two points that are closer together than you expect!

If you can share your data, or your example code, I'd be happy to take a look.

**Comment by Dividuals** [comment]
Yes i saw that. I will check my data.

Here is my chart code (typescript) : http://pastebin.com/E8VbKjy7

And here is my data (json) : http://pastebin.com/sNdg9egp
(As you can see, i convert this data with the "_getData" function.)

**Comment by Dividuals** [comment]
After filtering my data (removing non correctly spaced points), it seems to work.

I have also added weekend discontinuity provider, without unexpected candlestick width;

Thanks you for your fast response.

**Comment by Dividuals** [comment]
After filtering my data (removing non correctly spaced points), it seems to work.

I have also added weekend discontinuity provider, without unexpected candlestick width;

Thanks you for your fast response.

**Comment by Dividuals** [comment]
NOTE: It was due to summer time change on data set.

**Comment by ColinEberhardt** [comment]
Glad you've got it fixed.

> NOTE: It was due to summer time change on data set.

That old chestnut! UTC rules ;-)

**Comment by Dividuals** [comment]
Not really fixed, still have to find a way to handle summer time change.

Anyway, thank you again for your help.
