### ISSUE TITLE
Bollinger bands example is cut-off at beginning of chart

### ISSUE THREAD

**Issue by oriondean** [ScottLogic/d3fc#864]
See example at: https://d3fc.io/components/indicator/bollingerBands.html

Shouldn't the bands stretch across width of the chart?

I've noticed that other [examples](https://d3fc.io/examples/streaming/index.html) that feature bollinger bands do not have this issue anymore.

**Comment by ColinEberhardt** [comment]
Thanks @oriondean - that's been fixed
