### ISSUE TITLE
RSI renderer renders annotations above line

### ISSUE THREAD

**Issue by jleft** [ScottLogic/d3fc#865]
This is [inconsistent](https://github.com/ScottLogic/d3fc/blob/b04acf63ca2f0c4e38f958e6c7ac203e8be1c0ad/src/indicator/renderer/relativeStrengthIndex.js#L24) with the other indicator renderers which use annotations.

- [Stochastic Oscillator](https://github.com/ScottLogic/d3fc/blob/b04acf63ca2f0c4e38f958e6c7ac203e8be1c0ad/src/indicator/renderer/stochasticOscillator.js#L31)
- [Force Index](https://github.com/ScottLogic/d3fc/blob/b04acf63ca2f0c4e38f958e6c7ac203e8be1c0ad/src/indicator/renderer/forceIndex.js#L25)

I think this should be changed to be consistent with the other renderers listed above?

(https://github.com/ScottLogic/BitFlux/issues/603#issuecomment-179947213)

**Comment by ColinEberhardt** [comment]
Thanks @jleft - I like consistency!
