### ISSUE TITLE
Force index calculation is incomplete

### ISSUE THREAD

**Issue by jdhodges** [ScottLogic/d3fc#871]
The current implementation only calculates the force index for a single period. An exponential moving average is usually applied over multiple values to eliminate noise.

**Comment by jdhodges** [comment]
I'm currently working on a fix.

**Comment by ColinEberhardt** [comment]
That's great - thanks :-)

Can you please point to the reference you are using for Force Index? On that note, we have a book that contains descriptions of indicators and test data: http://blog.traderdealer.com.au/2011/02/04/trading-book-review-technical-analysis-from-a-z/

**Comment by jdhodges** [comment]
I have checked the book but unfortunately it has nothing about force index in it - I'm  currently using [this](http://investexcel.net/force-index-for-technical-traders/) site as a reference and for test data. Any chance we might have any other books where this could be covered?
