### ISSUE TITLE
Releases break the website until cdnjs updates

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/d3fc#873]
When performing a release, the website is built, linking to the new version, and the package published to npm. All good.

However, it takes a while for updates to reach cdnjs, the docs quote ~12hrs

https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md

**Comment by chrisprice** [comment]
What do we use cdnjs for? If it's just the quick start stuff, would a comment along those lines suffice?

**Comment by chrisprice** [comment]
Implication being if it's anything else we shouldn't be using cdnjs...

**Comment by ColinEberhardt** [comment]
CDNJS is used by the quick start and codepen. My plan is to resolve this by hosting our latest distribution builds on GitHub pages, using these for quick start and codepen, but also have a comment that points people at the cdn:

https://cdnjs.com/libraries/d3fc

**Comment by chrisprice** [comment]
As of #906 we no longer directly reference the cdnjs hosted versions.

**Comment by ColinEberhardt** [comment]
Another alternative, should we ever need it, is https://npmcdn.com/#/ - which updates more quickly than cdnjs.
