### ISSUE TITLE
cartesian chart x-axis label cropped in Safari

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/d3fc#877]
<img width="201" alt="screen shot 2016-02-10 at 22 12 42" src="https://cloud.githubusercontent.com/assets/1098110/12963626/9d730a26-d043-11e5-9e61-970f02726e43.png">

**Comment by ColinEberhardt** [comment]
Exploring further, Safari renders a number of dominant baseline values differently:

http://stackoverflow.com/questions/35565063/svg-dominant-baseline-not-working-in-safari

**Comment by chrisprice** [comment]
The MDN article for before/after edge specifies a browser dependency -
```
The baseline-identifier for the dominant-baseline is set to be text-after-edge. The derived baseline-table is constructed from the defined baselines in a baseline-table in the font. The choice of which font baseline-table to use from the baseline-tables in the font is browser dependent. The baseline-table font-size is changed to the value of the font-size attribute on this element.
```
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/dominant-baseline

Not suggesting this is the answer but it may be somewhere to start looking.

**Comment by chrisprice** [comment]
Baseline-shift might also be worth a look -https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/baseline-shift

**Comment by ColinEberhardt** [comment]
Thanks @chrisprice - I'll take a look at baseline-shift.

Safari also renders the ideographic dominant baseline differently as well. I couldn't find a decent image that illustrated the various baselines, so thought it was worth adding that to StackOverflow.

**Comment by ColinEberhardt** [comment]
@chrisprice good call with baseline-shift. It's to a perfect solution, but better than the current situation.
