### ISSUE TITLE
extent only allows a single point

### ISSUE THREAD

**Issue by jacknewberry** [ScottLogic/d3fc#911]
util.extent could maintain an _array_ of points which are always included in the extent.

Typically (and in my case) this will only contain 0 and a higher value required to give visual context to the graph.

```
#fc.util.extent.js
...
var includePoints = []
...
extent.include(singlePoint) -> add value to includePoints
extent.include([array of points]) -> append array to includePoints
extent.include() -> return includePoints
extent.include([]) -> empty includePoints
```

In the current implementation a second call to extent.include replaces the previous point.
This change would break extent if it is ever used with arrays as values.

**Comment by ColinEberhardt** [comment]
That's a good point, we hadn't considered the case where multiple points should be included within the range.

How about we simply change `include` so that it accepts an array of values? That way the property getters / setter is symmetrical, i.e. when you get the value it returns exactly the value that was set.

**Comment by jacknewberry** [comment]
Sounds good.

This is slightly strange:
```
x = 0
include(x)
include() == x:  // true

// has the same effect on the extent as:

include([x])
include() == x:  // false
```

but I think it is unlikely to cause problems because the person retrieving the value should know if it was set as an array. I also suspect that `include` is rarely used as a getter.

**Comment by chrisprice** [comment]
I would prefer not to auto-wrap any value for exactly the reason given. If a value is stored internally as an array then I think it should be set as an array. 

It would make this a breaking change but I think that's acceptable.

**Comment by ColinEberhardt** [comment]
@jacknewberry - I thought you might like to know that this updated has been released:

https://github.com/ScottLogic/d3fc/releases/tag/v7.0.0

You'll find it on npm and cdnjs (in a few hours)
