### ISSUE TITLE
Unable to get automatically generated tickValues on axis

### ISSUE THREAD

**Issue by rjmcneill** [ScottLogic/d3fc#914]
If we set the number of required ticks on ```fc.svg.axis()``` we can't get the actual tickValues returned.
The behaviour is demonstrated [here.] (http://codepen.io/rjmcneill/pen/aNoLKY?editors=0011)

I have 4 solutions, and I'm happy to submit a PR if you think any are along the right lines.

- [One] (https://github.com/rjmcneill/d3fc/tree/bug/tick-values-1)
- [Two] (https://github.com/rjmcneill/d3fc/tree/bug/tick-values-2)
- [Three] (https://github.com/rjmcneill/d3fc/tree/bug/tick-values-3)
- [Four] (https://github.com/rjmcneill/d3fc/tree/bug/tick-values-4)

**Comment by chrisprice** [comment]
The existing behavior seems consistent with d3 -

https://github.com/mbostock/d3/wiki/SVG-Axes#tickValues

**Comment by ColinEberhardt** [comment]
The axis delegates to the scale to determine the ticks - so how about obtaining them as follows:

`dateAxis.scale().ticks()`

**Comment by rjmcneill** [comment]
Thanks for the feedback @chrisprice and @ColinEberhardt.
Obtaining them through scale seems like a good solution.
Cheers!

**Comment by ColinEberhardt** [comment]
No problem :-)
