### ISSUE TITLE
groupedBar series should allow grouping of other series types

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/d3fc#915]
See this example:

![](http://i.stack.imgur.com/QtazN.png)

This should be a pretty trivial change.

**Comment by rjmcneill** [comment]
Would this be wanted just for these series:
- Box plot
- Error bar
- Stacked

**Comment by ColinEberhardt** [comment]
I'd try to make it as generic as possible. All the grouped series really does is apply some offset to the points of a series and sets the `barWdith`. If you change the implementation so that it tests for the presence of the `barWidth` property before invoking it, I would guess that it could work with any series.

You might want to consider taking the 'sub series' as constructor argument - this side-steps the problem of which properties to rebind!

Come and give me a shout if you want to discuss the implementation ...

**Comment by ColinEberhardt** [comment]
Just stumbled on this, another example ....

http://www.nature.com/ncomms/2014/140422/ncomms4679/fig_tab/ncomms4679_F2.html
