### ISSUE TITLE
Low barrel example chart throws lots of errors

### ISSUE THREAD

**Issue by alisd23** [ScottLogic/d3fc#937]
Errors occur on mouse move and on zoom.

![image](https://cloud.githubusercontent.com/assets/5804010/13740460/d204ef2c-e9c8-11e5-81ea-731c474b0b8b.png)

 Possibly something to do with the broken date labels below.

![image](https://cloud.githubusercontent.com/assets/5804010/13740540/328a9b30-e9c9-11e5-8521-266cc1d39b1b.png)

**Comment by ColinEberhardt** [comment]
I would have expected the CI build to pick up on that? Probably worth checking.

**Comment by chrisprice** [comment]
> occur on mouse move and on zoom

**Comment by ColinEberhardt** [comment]
RTFI?

**Comment by chrisprice** [comment]
Something like that :)
