### ISSUE TITLE
Unused imports are not being picked up by the linter

### ISSUE THREAD

**Issue by chrisprice** [ScottLogic/d3fc#940]
Feels like there should be an option to enable that?

**Comment by jdhodges** [comment]
I can't find anything specifically for detecting unused imports - [no-unused-vars](http://eslint.org/docs/rules/no-unused-vars) will do the job but will obviously cover more than just imports, should we go for that?

**Comment by chrisprice** [comment]
I can't see a good reason for having unused vars, so that sounds even
better!
