### ISSUE TITLE
No more Internet Explorer? 

### ISSUE THREAD

**Issue by renatobarbato** [ScottLogic/d3fc#946]
<img width="932" alt="schermata 2016-03-17 alle 20 54 01" src="https://cloud.githubusercontent.com/assets/17912984/13859177/72ad9bd4-ec82-11e5-81f3-7de8cca539c0.png">
IE 11

**Comment by chrisprice** [comment]
We'll investigate, looks like a bug. We haven't intentionally removed support.

**Comment by renatobarbato** [comment]
thank you Chris!
this is the error message:
Unhandled exception at line 10, column 25803 in https://d3fc.io/scripts.js
0x800a1391 - JavaScript runtime error: 'Symbol' is undefined

**Comment by chrisprice** [comment]
I've created a PR to address the main problem (add `babel-polyfill` to dist build) but there are still some rendering problems -

![image](https://cloud.githubusercontent.com/assets/433457/13888751/0765f754-ed3b-11e5-836e-526944cf3645.png)

In some places it works fine though, so I'm guessing it's some sort of timing issue.

**Comment by renatobarbato** [comment]
Now it works again, thank you
<img width="500" alt="schermata 2016-03-20 alle 08 48 51" src="https://cloud.githubusercontent.com/assets/17912984/13903389/cfc7a740-ee78-11e5-86eb-b4284ee1a557.png">
