### ISSUE TITLE
Small multiples chart doesn't allow different y axis domains

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/d3fc#947]
Our small multiple uses x and y scale for each chart. However, in some examples different domains are required for each multiple. See the following example:

http://bl.ocks.org/mbostock/1157787

**Comment by jdhodges** [comment]
I have implemented this so the domain can be set for each row (or column):

![image](https://cloud.githubusercontent.com/assets/14218569/14740561/ca00497e-0887-11e6-9102-5ec0899033b3.png)

Is this ok or do we want to render a separate axis for each individual multiple?

**Comment by ColinEberhardt** [comment]
Thanks for looking into this @jdhodges - I don't think you'd want different domains for each multiple, this would require rendering axes for each multiple, adding clutter.

**Comment by ColinEberhardt** [comment]
This was implemented via #963
