### ISSUE TITLE
GitHub releases do not include dist bundled files

### ISSUE THREAD

**Issue by jleft** [ScottLogic/d3fc#950]
I think it would be useful to also include the bundled d3fc files in GitHub releases (assuming GitHub releases is still relevant?).

Currently, only the following files are including:

![GitHub Releases](https://cloud.githubusercontent.com/assets/2017615/14124921/3768adde-f600-11e5-95ea-45a52812b233.png)

**Comment by ColinEberhardt** [comment]
GitHub releases are certainly relevant, although I don't know whether people use them to obtain the library (as we already have CDN, npm, etc .,.). Anyhow, it is pretty easy to provide our library via this release mechanism.
