### ISSUE TITLE
How can i add custom json data in D3FC chart .

### ISSUE THREAD

**Issue by saiyadhusain** [ScottLogic/d3fc#968]
Hello ,

i want to add my json to D3FC chart and apply data on all chart from my API . can you help me how i can do that . like in Streaming Candlestick i want to pass my json not random financial data . 

Regards 
Saiyad

**Comment by ColinEberhardt** [comment]
I'd recommend reading some of the in-depth tutorials on using JSON with D3:

https://www.dashingd3js.com/using-json-to-simplify-code
https://www.dashingd3js.com/d3-examples/1-d3-and-javascript-working-with-json
