### ISSUE TITLE
How to draw ohlc stock chart with discrete time?

### ISSUE THREAD

**Issue by Micjoyce** [ScottLogic/d3fc#985]
Hi, ya!
I  very much like this project, and I want to draw draw a stock chart with my own data, but I met a problem in the process of drawing, I provide the data is discrete in time, but I hope I painted figure is a continuous map, how do I draw?

There is my data
`
[[20150210,309512,309049,314210,308425,314159,193817139,225084911951],[20150211,314159,314577,316642,313905,315770,172840094,210862549367],[20150212,315770,315796,318177,313424,317342,194592309,229691579784],[20150213,317342,318681,323716,318279,320383,261290436,293017678939],[20150216,320383,320614,322885,319588,322236,223797429,265950695641],[20150217,322236,323088,325573,323077,324691,228332624,263340054080],[20150225,324691,325648,325722,321555,322884,233348094,265143351568],[20150226,322884,322215,330062,320219,329836,301263875,334347476047],[20150227,329836,329683,332455,329101,331030,299163717,335019568776],[20150302,331030,333272,333676,329867,333629,346445671,410259559474],[20150303,333629,331770,331770,326043,326305,382044619,441593480102],[20150304,326305,326418,328659,325048,327953,293639522,346789769320],[20150305,327953,326409,326664,322167,324848,320663585,373579996448],[20150306,324848,324804,326693,323453,324119,282915791,328344152930],[20150309,324119,322431,330770,319837,330241,321495440,359927522111],[20150310,330241,328909,330992,327710,328607,285817576,329955974292],[20150311,328607,328959,332505,327847,329090,282985535,327573066473]]
`
I hope you can give me some advice

Thank you!

**Comment by Micjoyce** [comment]
there is low-barrel discrete in time example
[https://codepen.io/Micjoyce/pen/vKGajM](url)

**Comment by ColinEberhardt** [comment]
You're going to have to tell us a bit more about your data in order to get some help. I guess each item in the array contains a datapoint with high / low / open / close / time / volume and other fields?

```
[20150311,328607,328959,332505,327847,329090,282985535,327573066473]
```

Can you describe what each item at each array index is?

**Comment by Micjoyce** [comment]
`
[20150210,309512,309049,314210,308425,314159,193817139,225084911951]
`

**Comment by rhewitt** [comment]
I just happen to have finished an evaluation of using D3FC for my own project, which needed the same thing. Turns out it's easy to do!

Since you're using a single point per day, just plot indexes as the X values instead of dates. Then decorate the chart with date labels corresponding to the tick indexes. I posted ![this gist](https://gist.github.com/rhewitt/3a170d58d8eff40fc1b858e1d9b1124d#file-d3fc-candlestick-with-date-gaps-html) you can use as an example. It looks like ![this](https://cloud.githubusercontent.com/assets/969372/16047929/e41bcc4a-3206-11e6-95c3-d232e4585aec.png)

Thanks, guys, D3FC is great!

**Comment by ColinEberhardt** [comment]
That's awesome - thanks @rhewitt 

I was going to suggest using some form of ordinal scale for the x-axis, although, linear axis works just as well, and also might be easier for adding interactions such as pan / zoom.

**Comment by Micjoyce** [comment]
Thanks @rhewitt , @ColinEberhardt 
I'm going to give it a try, but I have a question, if use linear scale, don't know in the realization of zoom/pan will have what problem, my ultimate goal is to achieve a low - barrel type stock chart.
There is a problem, have what good advice I can quickly grasp d3fc to draw?Can you give me some advice?

**Comment by rhewitt** [comment]
Hi @Micjoyce , are you asking if mapping dates to indexes will cause a problem when zooming or panning? It shouldn't. All this does is place the data at equally spaced intervals along the x axis. Dates themselves are just integers. The indexes are integers. Same thing, really. Except that you can easily ignore gaps by remapping to the indexes.

**Comment by rhewitt** [comment]
Let me correct myself here. More generally, dates are numbers and so are the indexes. They're not constrained to be integers; that's incidental. D3 will treat the values as floating point when they're rescaled to fit the axes.

**Comment by chrisprice** [comment]
Assuming the advice worked out 😃
