### ISSUE TITLE
How to draw custom disconnected lines

### ISSUE THREAD

**Issue by gargleblaster** [ScottLogic/d3fc#991]
I am trying to draw a line for each closed trade, from the opening date and price to the closing date and price.  Ideally, I would like to be able to decorate each line based on direction (long/short), quantity, gain/loss, etc.

I am taking advantage of the zoom and pan capabilities in low barrel [where does that name come from??], so I need to draw these lines using d3fc's scale settings to have them move with the candles.  But I'm not sure how to add simple d3 lines (with points x1, y1, and x2, y2) to the d3fc framework.  If I use fc.series.line(), it won't let me draw distinct lines.

Each line would be based off of the following data:

`                                account: t.account,
                                direction: t.direction,
                                openDate: moment(t.openDate).tz('America/New_York').format('YY-MM-DD HH:mm:ss'),
                                closeDate: moment(t.closeDate).tz('America/New_York').format('YY-MM-DD HH:mm:ss'),
                                openQty: t.openQty,
                                closeQty: t.closeQty,
                                openPrice: t.openPrice,
                                closePrice: t.closePrice,
                                gain: t.gain
`

What is the right way to do this in d3fc?

BTW, thanks for a very cool framework!

**Comment by chrisprice** [comment]
Maybe you could draw a quick sketch of what you're after to make it clear? But... it sounds like you want to draw n individual lines on the chart?

If so, I'd use `fc.series.multi` to wrap n `fc.series.line` instances. Whilst this modified low barrel (high stock...) example isn't exactly what you're after hopefully you can follow the gist of it -

https://codepen.io/anon/pen/VjKZgW?editors=0010

**Comment by gargleblaster** [comment]
Thanks for your reply, Chris.  This isn't a great sketch, but you can see that I have four disconnected lines with arbitrary endpoints, along with some annotations.  I suspect from your example that `fc.series.line` forces you to connect your lines.  Also, it is quite possible that I would want multiple lines that overlap partially or completely, so I'm thinking that `fc.series.line` will not allow that.

Would it work to make each individual line its own series?  I'm hungry for documentation.  I find the wiki pages and web site whets my appetite but does not satisfy my need for details on how to use the APIs.

![image](https://cloud.githubusercontent.com/assets/728163/16164778/02a5ec28-34ae-11e6-901c-b8739e62035e.png)

**Comment by chrisprice** [comment]
Ah that was just my laziness coming up with the example! It can render
arbitrary lines.

In my example the data rendered by a given line series is the item
corresponding to its index in the pairs array ```var pairs =
d3.pairs(data);```. If you swap out pairs for your real data you should be
good to go.

Another tip might be to combine the line series with a point series (using
another multi) to make it easier to position the labels at the end of the
lines.

I'll add some examples to the website to explain both of the above.

**Comment by chrisprice** [comment]
#992 contains the examples for the website I mentioned previously, I'll give @ColinEberhardt a chance to look over them before they go live.

> I'm hungry for documentation. I find the wiki pages and web site whets my appetite but does not satisfy my need for details on how to use the APIs.

The site is intended to provide high-level guides, component level documentation as well as some general examples of usage. As we've been breaking down the library into smaller modules, you might have noticed that we're gradually moving the component documentation into the module README files. Ultimately the site is probably going to look more like https://bl.ocks.org/.

I'd completely forgotten the wiki page existed, as it was very old and out of date I've removed it. 

One of the challenges I think we have is explaining that the library is meant to build on top of d3, not replace it. Therefore to get the most out of it, a user must be familiar with the concepts in d3, *then* bring in d3fc and its unique concepts (I suppose in many ways it's like the React/redux complexity discussion).

That said, we obviously want to support people as much as we reasonably can, so I'd be really interested in hearing what you think could be changed? If you could point to examples of other project's documentation that you find compelling that would be ideal?

**Comment by chrisprice** [comment]
Examples are here -

https://d3fc.io/examples/area-line-point/index.html

https://d3fc.io/examples/multi-line/index.html
