### ISSUE TITLE
Customize axis display with fc.chart.cartesian()?

### ISSUE THREAD

**Issue by joncursi** [ScottLogic/d3fc#995]
Hi - thanks for the great library!

I'm trying to customize the axis display (i.e. orientation, number of domain labels to show) with `fc.chart.cartesian()`. However, it seems to only accept scales, rather than axes.

```js
const xExtent = fc.util.extent()
      .fields([
        (d) => new Date(d.s * 1000),
      ])(data);
const xScale = fc.scale.dateTime()
    .domain(xExtent);
const xAxis = d3.svg.axis() // where do I specify?
      .scale(xScale)
      .orient('bottom');

const yExtent = fc.util.extent()
      .fields([
        (d) => d.c,
      ])
      .padUnit('percent')
      .pad(0.5)(data);
const yScale = d3.scale.linear()
    .domain(yExtent);
const yAxis = d3.svg.axis() // where do I specify?
      .scale(yScale)
      .orient('left');

const chart = fc.chart.cartesian(
      xScale,
      yScale)
      .xTicks(3)
      .yTicks(3)
      .margin({
        bottom: 30,
        right: 40,
      });
```

If i want to use custom axes, how do I specify this? Can this be done with `fc.chart.cartesian()`, or must I replace `fc.chart.cartesian()` and manually append my axes and series?

**Comment by chrisprice** [comment]
The `orient`ation of the yAxis used by the chart is exposed as `yOrient` on the `chart`. If you want to re-position it, just specify a custom `yBaseline` on the `chart`.

Here's a [quick example](https://codepen.io/anon/pen/mErNZe) -

```js
chart.yBaseline(0)
        .yOrient('left')
        .yTicks(4)
        .margin({ top: 10, right: 10, bottom: 20, left: 40 })
```

*In this case I've adjusted the margin as well to make way for the axis and reduced the tick count to make things look tidier.*

You can find the code which rebinds the axis properties [here](https://github.com/ScottLogic/d3fc/blob/master/src/chart/cartesian.js#L214).

**Comment by joncursi** [comment]
Thanks for your quick reply! The above example seems to work for me but only if I omit the `yBaseline` call, otherwise I get the following error:

```
Uncaught TypeError: endDate.getTime is not a function
```

Here my code snippet:

```js
const chart = fc.chart.cartesian(
  fc.scale.dateTime(),
  d3.scale.linear())
  .xDomain(xExtent)
  .yDomain(yExtent);

chart.yBaseline(0) // ~~ it errors on this line ~~
  .yOrient('left')
  .yTicks(3)
  .margin({ top: 10, right: 10, bottom: 20, left: 40 });
```

My x-axis uses a date scale, which seems to conflict with `yBaseline`. Any thoughts?

**Comment by ColinEberhardt** [comment]
The baseline for each axis determines its location with respect to the 'cross' axis. i.e. the `yBaseline` indicates the positions the y axis will occupy in the x-direction. The value you supply for the baseline must use the same units as the 'cross' axis.

In this case, your x axis uses a `dateTime` scale, and as a result your `yBaseline` should indicate the y axis location as a date.

**Comment by joncursi** [comment]
Ah that makes sense, thank you!
