### ISSUE TITLE
How to Set Layout Size for Cartesian Chart?

### ISSUE THREAD

**Issue by joncursi** [ScottLogic/d3fc#996]
Based on the documentation, it is unclear to me on how to properly set the layout dimensions of a cartesian chart using the cartesian API.

When I set the height and width attributes on the top-most DOM node (a div that wraps the chart), this div will take on the proper dimensions, however the `.cartesian-chart` element that gets rendered as a child within it calculates its own width and height dimensions which appear to be driven off of `layout-width` and `layout-height`. How can these values be customized at the time of render? I currently have:

```js
...

const chart = fc.chart.cartesian(
  xScale,
  yScale)
  .plotArea(plotArea);

d3.select('#price-chart') // top-level div DOM node
      .attr({
        height: chartHeight,
        width: chartWidth,
      })
      .datum(chartData)
      .call(chart);
```

`#price-chart` renders at 418x208
`.cartesian-chart` child renders only at 354x208, I would like it's width to be 100% (418px in this case)

Thanks!

**Comment by joncursi** [comment]
Here's a screengrab of the DOM nodes:

![screen_shot_2016-06-21_at_12_22_07_pm](https://cloud.githubusercontent.com/assets/4974609/16237530/ea4862b4-37aa-11e6-9e31-8aad45faea07.png)

`.cartesian-chart` does not inherit its size from the parent, it appears it needs to be specified separately, which I'm unsure how to do. Thanks!

**Comment by chrisprice** [comment]
Try setting width and height on the div using style rather than attr.
Non-SVG elements don't support those attributes.

You are correct that the chart will inherit it's containing elements
dimensions.

**Comment by chrisprice** [comment]
Assuming this fixed it.
